package eventlogstreaming

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

// DatadogConfig:
type DatadogConfig struct {
	// Site is one of the supported DatadogSite constants.
	Site DatadogSite `json:"site,omitempty"`
	// APIKey is the API key for submitting logs to a Datadog account.
	APIKey *string `json:"api_key,omitempty"`
}

// DatadogConfigMasked:
type DatadogConfigMasked struct {
	// APIKeyLastFour is the last four characters of the API key in use.
	APIKeyLastFour string `json:"api_key_last_four,omitempty"`
	// Site is one of the supported DatadogSite constants.
	Site DatadogSite `json:"site,omitempty"`
}
type DestinationConfig struct {
	Datadog     *DatadogConfig     `json:"datadog,omitempty"`
	GrafanaLoki *GrafanaLokiConfig `json:"grafana_loki,omitempty"`
}
type DestinationConfigMasked struct {
	Datadog     *DatadogConfigMasked     `json:"datadog,omitempty"`
	GrafanaLoki *GrafanaLokiConfigMasked `json:"grafana_loki,omitempty"`
}

// EventLogStreaming:
type EventLogStreaming struct {
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"destination_type,omitempty"`
	// DestinationConfig is the configuration for the destination to which to send events.
	DestinationConfig *DestinationConfig `json:"destination_config,omitempty"`
	StreamingStatus   StreamingStatus    `json:"streaming_status,omitempty"`
}

// EventLogStreamingMasked:
type EventLogStreamingMasked struct {
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"destination_type,omitempty"`
	// DestinationConfig is the configuration for the destination to which to send events.
	DestinationConfig *DestinationConfigMasked `json:"destination_config,omitempty"`
	StreamingStatus   StreamingStatus          `json:"streaming_status,omitempty"`
}

// GrafanaLokiConfig:
type GrafanaLokiConfig struct {
	// Hostname is the hostname of the Grafana Loki instance to which to send events.
	Hostname *string `json:"hostname,omitempty"`
	// Username is the username for authenticating the request to a Grafana Loki instance.
	Username *string `json:"username,omitempty"`
	// Password is the password for authenticating the request to a Grafana Loki instance.
	Password *string `json:"password,omitempty"`
}

// GrafanaLokiConfigMasked:
type GrafanaLokiConfigMasked struct {
	// Hostname is the hostname of the Grafana Loki instance to which to send events.
	Hostname string `json:"hostname,omitempty"`
	// Username is the username for authenticating the request to a Grafana Loki instance.
	Username string `json:"username,omitempty"`
	// PasswordLastFour is the last four characters of the password in use.
	PasswordLastFour string `json:"password_last_four,omitempty"`
}

// CreateRequest: Request type for `EventLogStreaming.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"destination_type,omitempty"`
	// DestinationConfig is the configuration for the destination to which to send events.
	DestinationConfig *DestinationConfig `json:"destination_config,omitempty"`
}

// CreateResponse: Response type for `EventLogStreaming.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EventLogStreamingConfig is the configuration that was created.
	EventLogStreamingConfig EventLogStreaming `json:"event_log_streaming_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `EventLogStreaming.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"-"`
}

// DeleteResponse: Response type for `EventLogStreaming.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DisableRequest: Request type for `EventLogStreaming.Disable`.
type DisableRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"-"`
}

// DisableResponse: Response type for `EventLogStreaming.Disable`.
type DisableResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// EnableRequest: Request type for `EventLogStreaming.Enable`.
type EnableRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"-"`
}

// EnableResponse: Response type for `EventLogStreaming.Enable`.
type EnableResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `EventLogStreaming.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"-"`
}

// GetResponse: Response type for `EventLogStreaming.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EventLogStreamingConfig is the event log streaming configuration.
	EventLogStreamingConfig EventLogStreamingMasked `json:"event_log_streaming_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `EventLogStreaming.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"-"`
	// DestinationConfig is the configuration for the destination to which to send events.
	DestinationConfig *DestinationConfig `json:"destination_config,omitempty"`
}

// UpdateResponse: Response type for `EventLogStreaming.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EventLogStreamingConfig is the configuration that was updated.
	EventLogStreamingConfig EventLogStreaming `json:"event_log_streaming_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type DatadogSite string

const (
	DatadogSiteUnknown DatadogSite = "DATADOG_SITE_UNSPECIFIED"
	DatadogSiteUs      DatadogSite = "US"
	DatadogSiteUs3     DatadogSite = "US3"
	DatadogSiteUs5     DatadogSite = "US5"
	DatadogSiteEu      DatadogSite = "EU"
	DatadogSiteAp1     DatadogSite = "AP1"
)

func DatadogSites() []DatadogSite {
	return []DatadogSite{
		DatadogSiteUs,
		DatadogSiteUs3,
		DatadogSiteUs5,
		DatadogSiteEu,
		DatadogSiteAp1,
	}
}

type DestinationType string

const (
	DestinationTypeUnknown     DestinationType = "DESTINATION_TYPE_UNSPECIFIED"
	DestinationTypeDatadog     DestinationType = "DATADOG"
	DestinationTypeGrafanaLoki DestinationType = "GRAFANA_LOKI"
)

func DestinationTypes() []DestinationType {
	return []DestinationType{
		DestinationTypeDatadog,
		DestinationTypeGrafanaLoki,
	}
}

type StreamingStatus string

const (
	StreamingStatusUnknown  StreamingStatus = "STREAMING_STATUS_UNSPECIFIED"
	StreamingStatusActive   StreamingStatus = "ACTIVE"
	StreamingStatusDisabled StreamingStatus = "DISABLED"
	StreamingStatusPending  StreamingStatus = "PENDING"
)

func StreamingStatuss() []StreamingStatus {
	return []StreamingStatus{
		StreamingStatusActive,
		StreamingStatusDisabled,
		StreamingStatusPending,
	}
}
