package eventlogstreaming

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type DatadogConfig struct {
	Site   DatadogSite `json:"site,omitempty"`
	APIKey *string     `json:"api_key,omitempty"`
}
type DatadogConfigMasked struct {
	APIKeyLastFour string      `json:"api_key_last_four,omitempty"`
	Site           DatadogSite `json:"site,omitempty"`
}
type DestinationConfig struct {
	Datadog     *DatadogConfig     `json:"datadog,omitempty"`
	GrafanaLoki *GrafanaLokiConfig `json:"grafana_loki,omitempty"`
}
type DestinationConfigMasked struct {
	Datadog     *DatadogConfigMasked     `json:"datadog,omitempty"`
	GrafanaLoki *GrafanaLokiConfigMasked `json:"grafana_loki,omitempty"`
}
type EventLogStreaming struct {
	DestinationType   DestinationType    `json:"destination_type,omitempty"`
	DestinationConfig *DestinationConfig `json:"destination_config,omitempty"`
	StreamingStatus   StreamingStatus    `json:"streaming_status,omitempty"`
}
type EventLogStreamingMasked struct {
	DestinationType   DestinationType          `json:"destination_type,omitempty"`
	DestinationConfig *DestinationConfigMasked `json:"destination_config,omitempty"`
	StreamingStatus   StreamingStatus          `json:"streaming_status,omitempty"`
}
type GrafanaLokiConfig struct {
	Hostname *string `json:"hostname,omitempty"`
	Username *string `json:"username,omitempty"`
	Password *string `json:"password,omitempty"`
}
type GrafanaLokiConfigMasked struct {
	Hostname         string `json:"hostname,omitempty"`
	Username         string `json:"username,omitempty"`
	PasswordLastFour string `json:"password_last_four,omitempty"`
}

// CreateRequest: Request type for `EventLogStreaming.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project for which to create the event log streaming config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to create the event log streaming config.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination to which to send events.
	DestinationType DestinationType `json:"destination_type,omitempty"`
	// DestinationConfig is the configuration for the destination to which to send events.
	DestinationConfig *DestinationConfig `json:"destination_config,omitempty"`
}

// CreateResponse: Response type for `EventLogStreaming.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EventLogStreamingConfig is the configuration that was created.
	EventLogStreamingConfig EventLogStreaming `json:"event_log_streaming_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `EventLogStreaming.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project for which to delete the event log streaming config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to delete the event log streaming config.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the destination type of the event log streaming config to delete.
	DestinationType DestinationType `json:"-"`
}

// DeleteResponse: Response type for `EventLogStreaming.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DisableRequest: Request type for `EventLogStreaming.Disable`.
type DisableRequest struct {
	// ProjectSlug is the slug of the project for which to disable the event log streaming config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to disable the event log streaming config.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the destination type of the event log streaming config to disable.
	DestinationType DestinationType `json:"-"`
}

// DisableResponse: Response type for `EventLogStreaming.Disable`.
type DisableResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// EnableRequest: Request type for `EventLogStreaming.Enable`.
type EnableRequest struct {
	// ProjectSlug is the slug of the project for which to enable the event log streaming config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to enable the event log streaming config.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the destination type of the event log streaming config to enable.
	DestinationType DestinationType `json:"-"`
}

// EnableResponse: Response type for `EventLogStreaming.Enable`.
type EnableResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `EventLogStreaming.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve the event log streaming config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve the event log streaming config.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the destination type of the event log streaming config to retrieve.
	DestinationType DestinationType `json:"-"`
}

// GetResponse: Response type for `EventLogStreaming.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EventLogStreamingConfig is the configuration that was created.
	EventLogStreamingConfig EventLogStreamingMasked `json:"event_log_streaming_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `EventLogStreaming.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project for which to update the event log streaming config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to update the event log streaming config.
	EnvironmentSlug string `json:"-"`
	// DestinationType is the type of destination for which to update the event log streaming config.
	DestinationType DestinationType `json:"-"`
	// DestinationConfig: DestinationType is the destination type of the event log streaming config to update.
	DestinationConfig *DestinationConfig `json:"destination_config,omitempty"`
}

// UpdateResponse: Response type for `EventLogStreaming.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EventLogStreamingConfig is the configuration that was created.
	EventLogStreamingConfig EventLogStreaming `json:"event_log_streaming_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type DatadogSite string

const (
	DatadogSiteUnknown DatadogSite = "DATADOG_SITE_UNSPECIFIED"
	DatadogSiteUs      DatadogSite = "US"
	DatadogSiteUs3     DatadogSite = "US3"
	DatadogSiteUs5     DatadogSite = "US5"
	DatadogSiteEu      DatadogSite = "EU"
	DatadogSiteAp1     DatadogSite = "AP1"
)

func DatadogSites() []DatadogSite {
	return []DatadogSite{
		DatadogSiteUs,
		DatadogSiteUs3,
		DatadogSiteUs5,
		DatadogSiteEu,
		DatadogSiteAp1,
	}
}

type DestinationType string

const (
	DestinationTypeUnknown     DestinationType = "DESTINATION_TYPE_UNSPECIFIED"
	DestinationTypeDatadog     DestinationType = "DATADOG"
	DestinationTypeGrafanaLoki DestinationType = "GRAFANA_LOKI"
)

func DestinationTypes() []DestinationType {
	return []DestinationType{
		DestinationTypeDatadog,
		DestinationTypeGrafanaLoki,
	}
}

type StreamingStatus string

const (
	StreamingStatusUnknown  StreamingStatus = "STREAMING_STATUS_UNSPECIFIED"
	StreamingStatusActive   StreamingStatus = "ACTIVE"
	StreamingStatusDisabled StreamingStatus = "DISABLED"
	StreamingStatusPending  StreamingStatus = "PENDING"
)

func StreamingStatuss() []StreamingStatus {
	return []StreamingStatus{
		StreamingStatusActive,
		StreamingStatusDisabled,
		StreamingStatusPending,
	}
}
