package emailtemplates

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type CustomHTMLCustomization struct {
	TemplateType     TemplateType `json:"template_type,omitempty"`
	HTMLContent      *string      `json:"html_content,omitempty"`
	PlaintextContent *string      `json:"plaintext_content,omitempty"`
	Subject          *string      `json:"subject,omitempty"`
}
type EmailTemplate struct {
	TemplateID              string                   `json:"template_id,omitempty"`
	Name                    *string                  `json:"name,omitempty"`
	SenderInformation       *SenderInformation       `json:"sender_information,omitempty"`
	PrebuiltCustomization   *PrebuiltCustomization   `json:"prebuilt_customization,omitempty"`
	CustomHTMLCustomization *CustomHTMLCustomization `json:"custom_html_customization,omitempty"`
}
type PrebuiltCustomization struct {
	ButtonBorderRadius *float32      `json:"button_border_radius,omitempty"`
	ButtonColor        *string       `json:"button_color,omitempty"`
	ButtonTextColor    *string       `json:"button_text_color,omitempty"`
	FontFamily         FontFamily    `json:"font_family,omitempty"`
	LogoSrc            *string       `json:"logo_src,omitempty"`
	TextAlignment      TextAlignment `json:"text_alignment,omitempty"`
}
type SenderInformation struct {
	FromLocalPart    *string `json:"from_local_part,omitempty"`
	FromDomain       *string `json:"from_domain,omitempty"`
	FromName         *string `json:"from_name,omitempty"`
	ReplyToLocalPart *string `json:"reply_to_local_part,omitempty"`
	ReplyToName      *string `json:"reply_to_name,omitempty"`
}

// CreateRequest: Request type for `EmailTemplates.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project for which to create the email template. An email template will be
	// created in each environment associated with this project.
	ProjectSlug string `json:"-"`
	// TemplateID is a unique identifier to use for the template – this is how you will refer to the template
	// when sending emails from your project or managing this template. It can never be changed after creation.
	TemplateID string `json:"template_id,omitempty"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name *string `json:"name,omitempty"`
	// SenderInformation is information about the email sender, such as the reply address or rendered name.
	// This is an optional field for PrebuiltCustomization, but required for CustomHTMLCustomization.
	SenderInformation *SenderInformation `json:"sender_information,omitempty"`
	// PrebuiltCustomization: NOTE: Only *one of these fields* should be set. PrebuiltCustomization is
	// customization related to prebuilt fields (such as button color) for prebuilt email templates.
	PrebuiltCustomization   *PrebuiltCustomization   `json:"prebuilt_customization,omitempty"`
	CustomHTMLCustomization *CustomHTMLCustomization `json:"custom_html_customization,omitempty"`
}

// CreateResponse: Response type for `EmailTemplates.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EmailTemplate is the email template that was created.
	EmailTemplate EmailTemplate `json:"email_template,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `EmailTemplates.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project for which to delete the email template. The email template will
	// be deleted in each environment associated with the project.
	ProjectSlug string `json:"-"`
	// TemplateID is the unique template ID for the email template to be deleted
	TemplateID string `json:"-"`
}

// DeleteResponse: Response type for `EmailTemplates.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `EmailTemplates.GetAll`.
type GetAllRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve all the email templates.
	ProjectSlug string `json:"-"`
}

// GetAllResponse: Response type for `EmailTemplates.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EmailTemplates is a list of all active email templates for the project.
	EmailTemplates []EmailTemplate `json:"email_templates,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetDefaultRequest: Request type for `EmailTemplates.GetDefault`.
type GetDefaultRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve allowed SMS country codes.
	ProjectSlug string `json:"-"`
	// EmailTemplateType is the template type for which to get the default email template.
	EmailTemplateType TemplateType `json:"-"`
}

// GetDefaultResponse: Response type for `EmailTemplates.GetDefault`.
type GetDefaultResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// TemplateID is a unique identifier to use for the template – this is how you will refer to the template
	// when sending emails from your project or managing this template. It can never be changed after creation.
	TemplateID string `json:"template_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `EmailTemplates.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project for which to get the default email template.
	ProjectSlug string `json:"-"`
	// TemplateID is the unique template ID for the email template to retrieve.
	TemplateID string `json:"-"`
}

// GetResponse: Response type for `EmailTemplates.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EmailTemplate is the email template that was created.
	EmailTemplate EmailTemplate `json:"email_template,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetDefaultRequest: Request type for `EmailTemplates.SetDefault`.
type SetDefaultRequest struct {
	// ProjectSlug is the slug of the project for which to set the default email template.
	ProjectSlug string `json:"-"`
	// TemplateID is a unique identifier to use for the template – this is how you will refer to the template
	// when sending emails from your project or managing this template. It can never be changed after creation.
	TemplateID string `json:"template_id,omitempty"`
	// EmailTemplateType is the template type for which to get the default email template.
	EmailTemplateType TemplateType `json:"-"`
}

// SetDefaultResponse: Response type for `EmailTemplates.SetDefault`.
type SetDefaultResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UnsetDefaultRequest: Request type for `EmailTemplates.UnsetDefault`.
type UnsetDefaultRequest struct {
	// ProjectSlug is the slug of the project for which to unset the default email template.
	ProjectSlug string `json:"-"`
	// EmailTemplateType is the template type for which to get the default email template.
	EmailTemplateType TemplateType `json:"-"`
}

// UnsetDefaultResponse: Response type for `EmailTemplates.UnsetDefault`.
type UnsetDefaultResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `EmailTemplates.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project for which to update the email template. The email template will
	// be updated in each environment associated with the project.
	ProjectSlug string `json:"-"`
	// TemplateID is a unique identifier to use for the template – this is how you will refer to the template
	// when sending emails from your project or managing this template. It can never be changed after creation.
	TemplateID string `json:"-"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name *string `json:"name,omitempty"`
	// SenderInformation is information about the email sender, such as the reply address or rendered name.
	// This is an optional field for PrebuiltCustomization, but required for CustomHTMLCustomization.
	SenderInformation *SenderInformation `json:"sender_information,omitempty"`
	// PrebuiltCustomization: NOTE: Only *one of these fields* should be set. PrebuiltCustomization is
	// customization related to prebuilt fields (such as button color) for prebuilt email templates.
	PrebuiltCustomization   *PrebuiltCustomization   `json:"prebuilt_customization,omitempty"`
	CustomHTMLCustomization *CustomHTMLCustomization `json:"custom_html_customization,omitempty"`
}

// UpdateResponse: Response type for `EmailTemplates.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// EmailTemplate is the email template that was created.
	EmailTemplate EmailTemplate `json:"email_template,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type FontFamily string

const (
	FontFamilyUnknown       FontFamily = "UNKNOWN_FONT_FAMILY"
	FontFamilyArial         FontFamily = "ARIAL"
	FontFamilyBrushScriptMT FontFamily = "BRUSH_SCRIPT_MT"
	FontFamilyCourierNew    FontFamily = "COURIER_NEW"
	FontFamilyGeorgia       FontFamily = "GEORGIA"
	FontFamilyHelvetica     FontFamily = "HELVETICA"
	FontFamilyTahoma        FontFamily = "TAHOMA"
	FontFamilyTimesNewRoman FontFamily = "TIMES_NEW_ROMAN"
	FontFamilyTrebuchetMS   FontFamily = "TREBUCHET_MS"
	FontFamilyVerdana       FontFamily = "VERDANA"
)

func FontFamilies() []FontFamily {
	return []FontFamily{
		FontFamilyArial,
		FontFamilyBrushScriptMT,
		FontFamilyCourierNew,
		FontFamilyGeorgia,
		FontFamilyHelvetica,
		FontFamilyTahoma,
		FontFamilyTimesNewRoman,
		FontFamilyTrebuchetMS,
		FontFamilyVerdana,
	}
}

type TemplateType string

const (
	TemplateTypeUnknown                  TemplateType = "UNKNOWN_TEMPLATE_TYPE"
	TemplateTypeLogin                    TemplateType = "LOGIN"
	TemplateTypeSignup                   TemplateType = "SIGNUP"
	TemplateTypeInvite                   TemplateType = "INVITE"
	TemplateTypeResetPassword            TemplateType = "RESET_PASSWORD"
	TemplateTypeOneTimePasscode          TemplateType = "ONE_TIME_PASSCODE"
	TemplateTypeOneTimePasscodeSignup    TemplateType = "ONE_TIME_PASSCODE_SIGNUP"
	TemplateTypeVerifyEmailPasswordReset TemplateType = "VERIFY_EMAIL_PASSWORD_RESET"
	TemplateTypeUnlock                   TemplateType = "UNLOCK"
	TemplateTypePrebuilt                 TemplateType = "PREBUILT"
)

func TemplateTypes() []TemplateType {
	return []TemplateType{
		TemplateTypeLogin,
		TemplateTypeSignup,
		TemplateTypeInvite,
		TemplateTypeResetPassword,
		TemplateTypeOneTimePasscode,
		TemplateTypeOneTimePasscodeSignup,
		TemplateTypeVerifyEmailPasswordReset,
		TemplateTypeUnlock,
		TemplateTypePrebuilt,
	}
}

type TextAlignment string

const (
	TextAlignmentUnknown TextAlignment = "UNKNOWN_TEXT_ALIGNMENT"
	TextAlignmentLeft    TextAlignment = "LEFT"
	TextAlignmentCenter  TextAlignment = "CENTER"
)

func TextAlignments() []TextAlignment {
	return []TextAlignment{
		TextAlignmentLeft,
		TextAlignmentCenter,
	}
}
