package publictokens

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import "time"

type PublicToken struct {
	PublicToken string    `json:"public_token,omitempty"`
	CreatedAt   time.Time `json:"created_at,omitempty"`
}

// CreateRequest: Request type for `PublicTokens.Create`.
type CreateRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// CreateResponse: Response type for `PublicTokens.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PublicToken is the public token value as well as the unique identifier for the token.
	PublicToken PublicToken `json:"public_token,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `PublicTokens.Delete`.
type DeleteRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// PublicToken is the public token value as well as the unique identifier for the token.
	PublicToken string `json:"-"`
}

// DeleteResponse: Response type for `PublicTokens.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `PublicTokens.GetAll`.
type GetAllRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetAllResponse: Response type for `PublicTokens.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PublicTokens is all the public tokens that belong to the environment.
	PublicTokens []PublicToken `json:"public_tokens,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `PublicTokens.Get`.
type GetRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// PublicToken is the public token value as well as the unique identifier for the token.
	PublicToken string `json:"-"`
}

// GetResponse: Response type for `PublicTokens.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PublicToken is the public token value as well as the unique identifier for the token.
	PublicToken PublicToken `json:"public_token,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}
