package jwttemplates

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type JWTTemplate struct {
	TemplateContent string          `json:"template_content,omitempty"`
	CustomAudience  string          `json:"custom_audience,omitempty"`
	JWTTemplateType JWTTemplateType `json:"jwt_template_type,omitempty"`
}

// GetRequest: Request type for `JWTTemplates.Get`.
type GetRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// JWTTemplateType is the type of JWT template.
	JWTTemplateType JWTTemplateType `json:"-"`
}

// GetResponse: Response type for `JWTTemplates.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// JWTTemplate is the JWT template for the requested JWTTemplateType.
	JWTTemplate JWTTemplate `json:"jwt_template,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetRequest: Request type for `JWTTemplates.Set`.
type SetRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// TemplateContent is the JWT template content.
	TemplateContent string `json:"template_content,omitempty"`
	// CustomAudience is an optional custom audience for the JWT template.
	CustomAudience string `json:"custom_audience,omitempty"`
	// JWTTemplateType is the type of JWT template.
	JWTTemplateType JWTTemplateType `json:"-"`
}

// SetResponse: Response type for `JWTTemplates.Set`.
type SetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// JWTTemplate is the JWT template for the requested JWTTemplateType.
	JWTTemplate JWTTemplate `json:"jwt_template,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type JWTTemplateType string

const (
	JWTTemplateTypeUnknown JWTTemplateType = "UNKNOWN_TEMPLATE_TYPE"
	JWTTemplateTypeSession JWTTemplateType = "SESSION"
	JWTTemplateTypeM2M     JWTTemplateType = "M2M"
)

func JWTTemplateTypes() []JWTTemplateType {
	return []JWTTemplateType{
		JWTTemplateTypeSession,
		JWTTemplateTypeM2M,
	}
}
