package projects

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import "time"

type Project struct {
	// ProjectSlug: The slug of the project.
	ProjectSlug string `json:"project_slug,omitempty"`
	// Name is a human-readable name. This does not have to be unique.
	Name string `json:"name,omitempty"`
	// Vertical is the project's vertical.
	Vertical Vertical `json:"vertical,omitempty"`
	// CreatedAt: The ISO-8601 timestamp for when the resource was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// CreateRequest: Request type for `Projects.Create`.
type CreateRequest struct {
	// Name is a human-readable name. This does not have to be unique.
	Name string `json:"name,omitempty"`
	// Vertical is the project's vertical.
	Vertical Vertical `json:"vertical,omitempty"`
	// ProjectSlug: The slug of the project.
	ProjectSlug *string `json:"project_slug,omitempty"`
}

// CreateResponse: Response type for `Projects.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Project contains the details for the newly created project.
	Project Project `json:"project,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `Projects.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
}

// DeleteResponse: Response type for `Projects.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `Projects.GetAll`.
type GetAllRequest struct{}

// GetAllResponse: Response type for `Projects.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Projects is a list of all active projects in the workspace.
	Projects []Project `json:"projects,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `Projects.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
}

// GetResponse: Response type for `Projects.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Project contains the project details.
	Project Project `json:"project,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `Projects.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// Name is a human-readable name. This does not have to be unique.
	Name *string `json:"name,omitempty"`
}

// UpdateResponse: Response type for `Projects.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Project contains the updated project details.
	Project Project `json:"project,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type Vertical string

const (
	VerticalUnknown  Vertical = "UNKNOWN"
	VerticalAll      Vertical = "ALL"
	VerticalConsumer Vertical = "CONSUMER"
	VerticalB2B      Vertical = "B2B"
)

func Verticals() []Vertical {
	return []Vertical{
		VerticalAll,
		VerticalConsumer,
		VerticalB2B,
	}
}
