package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/countrycodeallowlist"
)

type CountryCodeAllowlistClient struct {
	client *internal.Client
}

func newCountryCodeAllowlistClient(c *internal.Client) *CountryCodeAllowlistClient {
	return &CountryCodeAllowlistClient{
		client: c,
	}
}

// GetAllowedSMSCountryCodes retrieves the allowed SMS country codes for an environment.
func (c *CountryCodeAllowlistClient) GetAllowedSMSCountryCodes(
	ctx context.Context,
	body countrycodeallowlist.GetAllowedSMSCountryCodesRequest,
) (*countrycodeallowlist.GetAllowedSMSCountryCodesResponse, error) {
	var resp countrycodeallowlist.GetAllowedSMSCountryCodesResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/allowed_country_codes/sms", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAllowedWhatsAppCountryCodes retrieves the allowed WhatsApp country codes for an environment.
func (c *CountryCodeAllowlistClient) GetAllowedWhatsAppCountryCodes(
	ctx context.Context,
	body countrycodeallowlist.GetAllowedWhatsAppCountryCodesRequest,
) (*countrycodeallowlist.GetAllowedWhatsAppCountryCodesResponse, error) {
	var resp countrycodeallowlist.GetAllowedWhatsAppCountryCodesResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/allowed_country_codes/whatsapp", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetAllowedSMSCountryCodes sets the allowed SMS country codes for an environment.
func (c *CountryCodeAllowlistClient) SetAllowedSMSCountryCodes(
	ctx context.Context,
	body countrycodeallowlist.SetAllowedSMSCountryCodesRequest,
) (*countrycodeallowlist.SetAllowedSMSCountryCodesResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp countrycodeallowlist.SetAllowedSMSCountryCodesResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/allowed_country_codes/sms", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetAllowedWhatsAppCountryCodes sets the allowed WhatsApp country codes for an environment.
func (c *CountryCodeAllowlistClient) SetAllowedWhatsAppCountryCodes(
	ctx context.Context,
	body countrycodeallowlist.SetAllowedWhatsAppCountryCodesRequest,
) (*countrycodeallowlist.SetAllowedWhatsAppCountryCodesResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp countrycodeallowlist.SetAllowedWhatsAppCountryCodesResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/allowed_country_codes/whatsapp", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
