package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/eventlogstreaming"
)

type EventLogStreamingClient struct {
	client *internal.Client
}

func newEventLogStreamingClient(c *internal.Client) *EventLogStreamingClient {
	return &EventLogStreamingClient{
		client: c,
	}
}

// Create creates an event log streaming config for an environment.
func (c *EventLogStreamingClient) Create(
	ctx context.Context,
	body eventlogstreaming.CreateRequest,
) (*eventlogstreaming.CreateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp eventlogstreaming.CreateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/event_log_streaming", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Delete deletes an event log streaming config for an environment.
func (c *EventLogStreamingClient) Delete(
	ctx context.Context,
	body eventlogstreaming.DeleteRequest,
) (*eventlogstreaming.DeleteResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.DestinationType == "" {
		return nil, fmt.Errorf("DestinationType cannot be empty")
	}
	var resp eventlogstreaming.DeleteResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/event_log_streaming/%s", body.ProjectSlug, body.EnvironmentSlug, body.DestinationType),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Disable stops streaming event logs for an environment to a destination.
func (c *EventLogStreamingClient) Disable(
	ctx context.Context,
	body eventlogstreaming.DisableRequest,
) (*eventlogstreaming.DisableResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.DestinationType == "" {
		return nil, fmt.Errorf("DestinationType cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp eventlogstreaming.DisableResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/event_log_streaming/%s/disable", body.ProjectSlug, body.EnvironmentSlug, body.DestinationType),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Enable starts streaming event logs for an environment to a destination.
func (c *EventLogStreamingClient) Enable(
	ctx context.Context,
	body eventlogstreaming.EnableRequest,
) (*eventlogstreaming.EnableResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.DestinationType == "" {
		return nil, fmt.Errorf("DestinationType cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp eventlogstreaming.EnableResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/event_log_streaming/%s/enable", body.ProjectSlug, body.EnvironmentSlug, body.DestinationType),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Get retrieves an event log streaming config for an environment.
func (c *EventLogStreamingClient) Get(
	ctx context.Context,
	body eventlogstreaming.GetRequest,
) (*eventlogstreaming.GetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.DestinationType == "" {
		return nil, fmt.Errorf("DestinationType cannot be empty")
	}
	var resp eventlogstreaming.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/event_log_streaming/%s", body.ProjectSlug, body.EnvironmentSlug, body.DestinationType),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Update updates an event log streaming config for an environment.
func (c *EventLogStreamingClient) Update(
	ctx context.Context,
	body eventlogstreaming.UpdateRequest,
) (*eventlogstreaming.UpdateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.DestinationType == "" {
		return nil, fmt.Errorf("DestinationType cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp eventlogstreaming.UpdateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/event_log_streaming/%s", body.ProjectSlug, body.EnvironmentSlug, body.DestinationType),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
