package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/passwordstrengthconfig"
)

type PasswordStrengthConfigClient struct {
	client *internal.Client
}

func newPasswordStrengthConfigClient(c *internal.Client) *PasswordStrengthConfigClient {
	return &PasswordStrengthConfigClient{
		client: c,
	}
}

// Get retrieves the password strength configuration for an environment.
func (c *PasswordStrengthConfigClient) Get(
	ctx context.Context,
	body passwordstrengthconfig.GetRequest,
) (*passwordstrengthconfig.GetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	var resp passwordstrengthconfig.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/password_strength_config", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Set updates the password strength configuration for an environment.
func (c *PasswordStrengthConfigClient) Set(
	ctx context.Context,
	body passwordstrengthconfig.SetRequest,
) (*passwordstrengthconfig.SetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp passwordstrengthconfig.SetResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/password_strength_config", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
