package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/projects"
)

type ProjectsClient struct {
	client *internal.Client
}

func newProjectsClient(c *internal.Client) *ProjectsClient {
	return &ProjectsClient{
		client: c,
	}
}

// Create creates a project, including both a live and test environment.
func (c *ProjectsClient) Create(
	ctx context.Context,
	body projects.CreateRequest,
) (*projects.CreateResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp projects.CreateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		"/pwa/v3/projects",
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Delete deletes a project and all of its environments.
func (c *ProjectsClient) Delete(
	ctx context.Context,
	body projects.DeleteRequest,
) (*projects.DeleteResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	var resp projects.DeleteResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/pwa/v3/projects/%s", body.ProjectSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Get retrieves a project.
func (c *ProjectsClient) Get(
	ctx context.Context,
	body projects.GetRequest,
) (*projects.GetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	var resp projects.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s", body.ProjectSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAll retrieves all projects in a workspace.
func (c *ProjectsClient) GetAll(
	ctx context.Context,
	body projects.GetAllRequest,
) (*projects.GetAllResponse, error) {
	var resp projects.GetAllResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		"/pwa/v3/projects",
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Update updates the project.
func (c *ProjectsClient) Update(
	ctx context.Context,
	body projects.UpdateRequest,
) (*projects.UpdateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp projects.UpdateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPatch,
		fmt.Sprintf("/pwa/v3/projects/%s", body.ProjectSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
