package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/rbacpolicy"
)

type RBACPolicyClient struct {
	client *internal.Client
}

func newRBACPolicyClient(c *internal.Client) *RBACPolicyClient {
	return &RBACPolicyClient{
		client: c,
	}
}

// Get retrieves the RBAC policy for an environment.
func (c *RBACPolicyClient) Get(
	ctx context.Context,
	body rbacpolicy.GetRequest,
) (*rbacpolicy.GetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	var resp rbacpolicy.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/rbac_policy", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Set updates the RBAC policy for an environment.
func (c *RBACPolicyClient) Set(
	ctx context.Context,
	body rbacpolicy.SetRequest,
) (*rbacpolicy.SetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp rbacpolicy.SetResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/rbac_policy", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
