package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/redirecturls"
)

type RedirectURLsClient struct {
	client *internal.Client
}

func newRedirectURLsClient(c *internal.Client) *RedirectURLsClient {
	return &RedirectURLsClient{
		client: c,
	}
}

// Create creates a redirect URL for an environment.
func (c *RedirectURLsClient) Create(
	ctx context.Context,
	body redirecturls.CreateRequest,
) (*redirecturls.CreateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp redirecturls.CreateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/redirect_urls", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Delete deletes a redirect URL for an environment.
func (c *RedirectURLsClient) Delete(
	ctx context.Context,
	body redirecturls.DeleteRequest,
) (*redirecturls.DeleteResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	queryParams := make(map[string]string)
	queryParams["url"] = body.URL
	if body.DoNotPromoteDefaults != nil {
		if *body.DoNotPromoteDefaults {
			queryParams["do_not_promote_defaults"] = "true"
		} else {
			queryParams["do_not_promote_defaults"] = "false"
		}
	}

	var resp redirecturls.DeleteResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/redirect_urls", body.ProjectSlug, body.EnvironmentSlug),
		queryParams,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Get retrieves a redirect URL for an environment.
func (c *RedirectURLsClient) Get(
	ctx context.Context,
	body redirecturls.GetRequest,
) (*redirecturls.GetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	queryParams := make(map[string]string)
	queryParams["url"] = body.URL

	var resp redirecturls.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/redirect_urls", body.ProjectSlug, body.EnvironmentSlug),
		queryParams,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAll retrieves all redirect URLs for an environment.
func (c *RedirectURLsClient) GetAll(
	ctx context.Context,
	body redirecturls.GetAllRequest,
) (*redirecturls.GetAllResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	var resp redirecturls.GetAllResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/redirect_urls/all", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Update updates the valid types for a redirect URL for an environment.
func (c *RedirectURLsClient) Update(
	ctx context.Context,
	body redirecturls.UpdateRequest,
) (*redirecturls.UpdateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	queryParams := make(map[string]string)
	queryParams["url"] = body.URL

	var resp redirecturls.UpdateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/redirect_urls", body.ProjectSlug, body.EnvironmentSlug),
		queryParams,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
