package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/sdk"
)

type SDKClient struct {
	client *internal.Client
}

func newSDKClient(c *internal.Client) *SDKClient {
	return &SDKClient{
		client: c,
	}
}

// GetB2BConfig retrieves the SDK configuration for a B2B project environment
func (c *SDKClient) GetB2BConfig(
	ctx context.Context,
	body sdk.GetB2BConfigRequest,
) (*sdk.GetB2BConfigResponse, error) {
	var resp sdk.GetB2BConfigResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/b2b", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetConsumerConfig retrieves the SDK configuration for a B2C project environment
func (c *SDKClient) GetConsumerConfig(
	ctx context.Context,
	body sdk.GetConsumerConfigRequest,
) (*sdk.GetConsumerConfigResponse, error) {
	var resp sdk.GetConsumerConfigResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/consumer", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetB2BConfig updates the SDK configuration for a B2B project environment
func (c *SDKClient) SetB2BConfig(
	ctx context.Context,
	body sdk.SetB2BConfigRequest,
) (*sdk.SetB2BConfigResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp sdk.SetB2BConfigResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/b2b", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetConsumerConfig updates the SDK configuration for a B2C project environment
func (c *SDKClient) SetConsumerConfig(
	ctx context.Context,
	body sdk.SetConsumerConfigRequest,
) (*sdk.SetConsumerConfigResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp sdk.SetConsumerConfigResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/consumer", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
