package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/sdk"
)

type SDKClient struct {
	client *internal.Client
}

func newSDKClient(c *internal.Client) *SDKClient {
	return &SDKClient{
		client: c,
	}
}

// GetB2BSDKConfig: GetB2BConfig retrieves the SDK configuration for a B2B project environment
func (c *SDKClient) GetB2BSDKConfig(
	ctx context.Context,
	body sdk.GetB2BSDKConfigRequest,
) (*sdk.GetB2BSDKConfigResponse, error) {
	var resp sdk.GetB2BSDKConfigResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/b2b", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetConsumerSDKConfig: GetConsumerConfig retrieves the SDK configuration for a B2C project environment
func (c *SDKClient) GetConsumerSDKConfig(
	ctx context.Context,
	body sdk.GetConsumerSDKConfigRequest,
) (*sdk.GetConsumerSDKConfigResponse, error) {
	var resp sdk.GetConsumerSDKConfigResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/consumer", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetB2BSDKConfig: SetB2BConfig updates the SDK configuration for a B2B project environment
func (c *SDKClient) SetB2BSDKConfig(
	ctx context.Context,
	body sdk.SetB2BSDKConfigRequest,
) (*sdk.SetB2BSDKConfigResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp sdk.SetB2BSDKConfigResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/b2b", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// SetConsumerSDKConfig: SetConsumerConfig updates the SDK configuration for a B2C project environment
func (c *SDKClient) SetConsumerSDKConfig(
	ctx context.Context,
	body sdk.SetConsumerSDKConfigRequest,
) (*sdk.SetConsumerSDKConfigResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp sdk.SetConsumerSDKConfigResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPut,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/sdk/consumer", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
