package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/secrets"
)

type SecretsClient struct {
	client *internal.Client
}

func newSecretsClient(c *internal.Client) *SecretsClient {
	return &SecretsClient{
		client: c,
	}
}

// Create creates a secret for an environment. The response contains the full secret value, which will not
// be exposed in future Get requests.
func (c *SecretsClient) Create(
	ctx context.Context,
	body secrets.CreateRequest,
) (*secrets.CreateResponse, error) {
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp secrets.CreateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/secrets", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Delete deletes a secret for an environment.
func (c *SecretsClient) Delete(
	ctx context.Context,
	body secrets.DeleteRequest,
) (*secrets.DeleteResponse, error) {
	var resp secrets.DeleteResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/secrets/%s", body.ProjectSlug, body.EnvironmentSlug, body.SecretID),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Get retrieves a secret for an environment.
func (c *SecretsClient) Get(
	ctx context.Context,
	body secrets.GetRequest,
) (*secrets.GetResponse, error) {
	var resp secrets.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/secrets/%s", body.ProjectSlug, body.EnvironmentSlug, body.SecretID),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAll: Get retrieves a secret for an environment.
func (c *SecretsClient) GetAll(
	ctx context.Context,
	body secrets.GetAllRequest,
) (*secrets.GetAllResponse, error) {
	var resp secrets.GetAllResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/secrets", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
