package api

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/stytchauth/stytch-management-go/v3/pkg/api/internal"
	"github.com/stytchauth/stytch-management-go/v3/pkg/models/trustedtokenprofiles"
)

type TrustedTokenProfilesClient struct {
	client *internal.Client
}

func newTrustedTokenProfilesClient(c *internal.Client) *TrustedTokenProfilesClient {
	return &TrustedTokenProfilesClient{
		client: c,
	}
}

// Create creates a trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) Create(
	ctx context.Context,
	body trustedtokenprofiles.CreateRequest,
) (*trustedtokenprofiles.CreateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp trustedtokenprofiles.CreateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// CreatePEMFile: CreatePEM creates a PEM file for a trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) CreatePEMFile(
	ctx context.Context,
	body trustedtokenprofiles.CreatePEMFileRequest,
) (*trustedtokenprofiles.CreatePEMFileResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.ProfileID == "" {
		return nil, fmt.Errorf("ProfileID cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp trustedtokenprofiles.CreatePEMFileResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPost,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles/%s/keys", body.ProjectSlug, body.EnvironmentSlug, body.ProfileID),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Delete deletes a trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) Delete(
	ctx context.Context,
	body trustedtokenprofiles.DeleteRequest,
) (*trustedtokenprofiles.DeleteResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.ProfileID == "" {
		return nil, fmt.Errorf("ProfileID cannot be empty")
	}
	var resp trustedtokenprofiles.DeleteResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles/%s", body.ProjectSlug, body.EnvironmentSlug, body.ProfileID),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// DeletePEMFile: DeletePEM deletes a PEM file for a trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) DeletePEMFile(
	ctx context.Context,
	body trustedtokenprofiles.DeletePEMFileRequest,
) (*trustedtokenprofiles.DeletePEMFileResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.ProfileID == "" {
		return nil, fmt.Errorf("ProfileID cannot be empty")
	}
	if body.PEMFileID == "" {
		return nil, fmt.Errorf("PEMFileID cannot be empty")
	}
	var resp trustedtokenprofiles.DeletePEMFileResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodDelete,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles/%s/keys/%s", body.ProjectSlug, body.EnvironmentSlug, body.ProfileID, body.PEMFileID),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Get retrieves the trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) Get(
	ctx context.Context,
	body trustedtokenprofiles.GetRequest,
) (*trustedtokenprofiles.GetResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.ProfileID == "" {
		return nil, fmt.Errorf("ProfileID cannot be empty")
	}
	var resp trustedtokenprofiles.GetResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles/%s", body.ProjectSlug, body.EnvironmentSlug, body.ProfileID),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetAll retrieves all the trusted token profiles for an environment.
func (c *TrustedTokenProfilesClient) GetAll(
	ctx context.Context,
	body trustedtokenprofiles.GetAllRequest,
) (*trustedtokenprofiles.GetAllResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	var resp trustedtokenprofiles.GetAllResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles", body.ProjectSlug, body.EnvironmentSlug),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// GetPEMFile: GetPEM retrieves a PEM file for a trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) GetPEMFile(
	ctx context.Context,
	body trustedtokenprofiles.GetPEMFileRequest,
) (*trustedtokenprofiles.GetPEMFileResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.ProfileID == "" {
		return nil, fmt.Errorf("ProfileID cannot be empty")
	}
	if body.PEMFileID == "" {
		return nil, fmt.Errorf("PEMFileID cannot be empty")
	}
	var resp trustedtokenprofiles.GetPEMFileResponse
	err := c.client.NewRequest(
		ctx,
		http.MethodGet,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles/%s/keys/%s", body.ProjectSlug, body.EnvironmentSlug, body.ProfileID, body.PEMFileID),
		nil,
		nil,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}

// Update updates a trusted token profile for an environment.
func (c *TrustedTokenProfilesClient) Update(
	ctx context.Context,
	body trustedtokenprofiles.UpdateRequest,
) (*trustedtokenprofiles.UpdateResponse, error) {
	if body.ProjectSlug == "" {
		return nil, fmt.Errorf("ProjectSlug cannot be empty")
	}
	if body.EnvironmentSlug == "" {
		return nil, fmt.Errorf("EnvironmentSlug cannot be empty")
	}
	if body.ProfileID == "" {
		return nil, fmt.Errorf("ProfileID cannot be empty")
	}
	jsonBody, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	var resp trustedtokenprofiles.UpdateResponse
	err = c.client.NewRequest(
		ctx,
		http.MethodPatch,
		fmt.Sprintf("/pwa/v3/projects/%s/environments/%s/trusted_token_profiles/%s", body.ProjectSlug, body.EnvironmentSlug, body.ProfileID),
		nil,
		jsonBody,
		&resp)
	if err != nil {
		return nil, err
	}
	return &resp, nil
}
