package sdk

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type AuthorizedB2BDomain struct {
	Domain      string `json:"domain,omitempty"`
	SlugPattern string `json:"slug_pattern,omitempty"`
}
type B2BBasicConfig struct {
	Enabled                 bool                  `json:"enabled,omitempty"`
	AllowSelfOnboarding     bool                  `json:"allow_self_onboarding,omitempty"`
	EnableMemberPermissions bool                  `json:"enable_member_permissions,omitempty"`
	Domains                 []AuthorizedB2BDomain `json:"domains,omitempty"`
	BundleIds               []string              `json:"bundle_ids,omitempty"`
}
type B2BConfig struct {
	Basic      *B2BBasicConfig      `json:"basic,omitempty"`
	Sessions   *B2BSessionsConfig   `json:"sessions,omitempty"`
	MagicLinks *B2BMagicLinksConfig `json:"magic_links,omitempty"`
	OAuth      *B2BOAuthConfig      `json:"oauth,omitempty"`
	TOTPs      *B2BTOTPsConfig      `json:"totps,omitempty"`
	SSO        *B2BSSOConfig        `json:"sso,omitempty"`
	OTPs       *B2BOTPsConfig       `json:"otps,omitempty"`
	DFPPA      *B2BDFPPAConfig      `json:"dfppa,omitempty"`
	Passwords  *B2BPasswordsConfig  `json:"passwords,omitempty"`
	Cookies    *B2BCookiesConfig    `json:"cookies,omitempty"`
}
type B2BCookiesConfig struct {
	HTTPOnly string `json:"http_only,omitempty"`
}
type B2BDFPPAConfig struct {
	Enabled     DFPPASetting           `json:"enabled,omitempty"`
	OnChallenge DFPPAOnChallengeAction `json:"on_challenge,omitempty"`
}
type B2BMagicLinksConfig struct {
	Enabled      bool `json:"enabled,omitempty"`
	PkceRequired bool `json:"pkce_required,omitempty"`
}
type B2BOAuthConfig struct {
	Enabled      bool `json:"enabled,omitempty"`
	PkceRequired bool `json:"pkce_required,omitempty"`
}
type B2BOTPsConfig struct {
	SMSEnabled          bool                  `json:"sms_enabled,omitempty"`
	SMSAutofillMetadata []SMSAutofillMetadata `json:"sms_autofill_metadata,omitempty"`
	EmailEnabled        bool                  `json:"email_enabled,omitempty"`
}
type B2BPasswordsConfig struct {
	Enabled                       bool `json:"enabled,omitempty"`
	PkceRequiredForPasswordResets bool `json:"pkce_required_for_password_resets,omitempty"`
}
type B2BSSOConfig struct {
	Enabled      bool `json:"enabled,omitempty"`
	PkceRequired bool `json:"pkce_required,omitempty"`
}
type B2BSessionsConfig struct {
	MaxSessionDurationMinutes int `json:"max_session_duration_minutes,omitempty"`
}
type B2BTOTPsConfig struct {
	CreateTOTPs bool `json:"create_totps,omitempty"`
	Enabled     bool `json:"enabled,omitempty"`
}
type ConsumerBasicConfig struct {
	Enabled   bool     `json:"enabled,omitempty"`
	Domains   []string `json:"domains,omitempty"`
	BundleIds []string `json:"bundle_ids,omitempty"`
}
type ConsumerBiometricsConfig struct {
	CreateBiometricsEnabled bool `json:"create_biometrics_enabled,omitempty"`
	Enabled                 bool `json:"enabled,omitempty"`
}
type ConsumerConfig struct {
	Basic         *ConsumerBasicConfig         `json:"basic,omitempty"`
	Sessions      *ConsumerSessionsConfig      `json:"sessions,omitempty"`
	MagicLinks    *ConsumerMagicLinksConfig    `json:"magic_links,omitempty"`
	OTPs          *ConsumerOTPsConfig          `json:"otps,omitempty"`
	OAuth         *ConsumerOAuthConfig         `json:"oauth,omitempty"`
	TOTPs         *ConsumerTOTPsConfig         `json:"totps,omitempty"`
	WebAuthn      *ConsumerWebAuthnConfig      `json:"webauthn,omitempty"`
	CryptoWallets *ConsumerCryptoWalletsConfig `json:"crypto_wallets,omitempty"`
	DFPPA         *ConsumerDFPPAConfig         `json:"dfppa,omitempty"`
	Biometrics    *ConsumerBiometricsConfig    `json:"biometrics,omitempty"`
	Passwords     *ConsumerPasswordsConfig     `json:"passwords,omitempty"`
	Cookies       *ConsumerCookiesConfig       `json:"cookies,omitempty"`
}
type ConsumerCookiesConfig struct {
	HTTPOnly string `json:"http_only,omitempty"`
}
type ConsumerCryptoWalletsConfig struct {
	Enabled      bool `json:"enabled,omitempty"`
	SiweRequired bool `json:"siwe_required,omitempty"`
}
type ConsumerDFPPAConfig struct {
	Enabled     DFPPASetting           `json:"enabled,omitempty"`
	OnChallenge DFPPAOnChallengeAction `json:"on_challenge,omitempty"`
}
type ConsumerMagicLinksConfig struct {
	LoginOrCreateEnabled bool `json:"login_or_create_enabled,omitempty"`
	SendEnabled          bool `json:"send_enabled,omitempty"`
	PkceRequired         bool `json:"pkce_required,omitempty"`
}
type ConsumerOAuthConfig struct {
	Enabled      bool `json:"enabled,omitempty"`
	PkceRequired bool `json:"pkce_required,omitempty"`
}
type ConsumerOTPsConfig struct {
	SMSLoginOrCreateEnabled      bool                  `json:"sms_login_or_create_enabled,omitempty"`
	WhatsappLoginOrCreateEnabled bool                  `json:"whatsapp_login_or_create_enabled,omitempty"`
	EmailLoginOrCreateEnabled    bool                  `json:"email_login_or_create_enabled,omitempty"`
	SMSSendEnabled               bool                  `json:"sms_send_enabled,omitempty"`
	WhatsappSendEnabled          bool                  `json:"whatsapp_send_enabled,omitempty"`
	EmailSendEnabled             bool                  `json:"email_send_enabled,omitempty"`
	SMSAutofillMetadata          []SMSAutofillMetadata `json:"sms_autofill_metadata,omitempty"`
}
type ConsumerPasswordsConfig struct {
	Enabled                       bool `json:"enabled,omitempty"`
	PkceRequiredForPasswordResets bool `json:"pkce_required_for_password_resets,omitempty"`
}
type ConsumerSessionsConfig struct {
	MaxSessionDurationMinutes int `json:"max_session_duration_minutes,omitempty"`
}
type ConsumerTOTPsConfig struct {
	CreateTOTPs bool `json:"create_totps,omitempty"`
	Enabled     bool `json:"enabled,omitempty"`
}
type ConsumerWebAuthnConfig struct {
	CreateWebAuthnS bool `json:"create_webauthn_s,omitempty"`
	Enabled         bool `json:"enabled,omitempty"`
}
type SMSAutofillMetadata struct {
	MetadataType  string `json:"metadata_type,omitempty"`
	MetadataValue string `json:"metadata_value,omitempty"`
	BundleID      string `json:"bundle_id,omitempty"`
	ID            int    `json:"id,omitempty"`
}

// GetB2BSDKConfigRequest: Request type for `SDK.GetB2BSDKConfig`.
type GetB2BSDKConfigRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetB2BSDKConfigResponse: Response type for `SDK.GetB2BSDKConfig`.
type GetB2BSDKConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the consumer project SDK configuration.
	Config B2BConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetConsumerSDKConfigRequest: Request type for `SDK.GetConsumerSDKConfig`.
type GetConsumerSDKConfigRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetConsumerSDKConfigResponse: Response type for `SDK.GetConsumerSDKConfig`.
type GetConsumerSDKConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the consumer project SDK configuration.
	Config ConsumerConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetB2BSDKConfigRequest: Request type for `SDK.SetB2BSDKConfig`.
type SetB2BSDKConfigRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// Config is the consumer project SDK configuration.
	Config *B2BConfig `json:"config,omitempty"`
}

// SetB2BSDKConfigResponse: Response type for `SDK.SetB2BSDKConfig`.
type SetB2BSDKConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the consumer project SDK configuration.
	Config B2BConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetConsumerSDKConfigRequest: Request type for `SDK.SetConsumerSDKConfig`.
type SetConsumerSDKConfigRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// Config is the consumer project SDK configuration.
	Config *ConsumerConfig `json:"config,omitempty"`
}

// SetConsumerSDKConfigResponse: Response type for `SDK.SetConsumerSDKConfig`.
type SetConsumerSDKConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the consumer project SDK configuration.
	Config ConsumerConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type DFPPAOnChallengeAction string

const (
	DFPPAOnChallengeActionUnknown        DFPPAOnChallengeAction = "UNKNOWN_DFPPA_ON_CHALLENGE_ACTION"
	DFPPAOnChallengeActionAllow          DFPPAOnChallengeAction = "ALLOW"
	DFPPAOnChallengeActionBlock          DFPPAOnChallengeAction = "BLOCK"
	DFPPAOnChallengeActionTriggerCaptcha DFPPAOnChallengeAction = "TRIGGER_CAPTCHA"
)

func DFPPAOnChallengeActions() []DFPPAOnChallengeAction {
	return []DFPPAOnChallengeAction{
		DFPPAOnChallengeActionAllow,
		DFPPAOnChallengeActionBlock,
		DFPPAOnChallengeActionTriggerCaptcha,
	}
}

type DFPPASetting string

const (
	DFPPASettingUnknown  DFPPASetting = "UNKNOWN_DFPPA_SETTING"
	DFPPASettingEnabled  DFPPASetting = "ENABLED"
	DFPPASettingPassive  DFPPASetting = "PASSIVE"
	DFPPASettingDisabled DFPPASetting = "DISABLED"
)

func DFPPASettings() []DFPPASetting {
	return []DFPPASetting{
		DFPPASettingEnabled,
		DFPPASettingPassive,
		DFPPASettingDisabled,
	}
}
