package sdk

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type AuthorizedB2BDomain struct {
	// Domain is the domain name. Stytch uses the same-origin policy to determine matches.
	Domain string `json:"domain,omitempty"`
	// SlugPattern is the slug pattern that can be used to support authentication flows specific to each
	// organization. An example value here might be 'https://{{slug}}.example.com'. The value **must** include
	// '{{slug}}' as a placeholder for the slug.
	SlugPattern string `json:"slug_pattern,omitempty"`
}

type B2BBasicConfig struct {
	// Enabled indicates whether the B2B project SDK is enabled. This allows the SDK to manage user and session
	// data.
	Enabled bool `json:"enabled,omitempty"`
	// AllowSelfOnboarding indicates whether self-onboarding is allowed for members in the SDK.
	AllowSelfOnboarding bool `json:"allow_self_onboarding,omitempty"`
	// EnableMemberPermissions indicates whether member permissions RBAC are enabled in the SDK.
	EnableMemberPermissions bool `json:"enable_member_permissions,omitempty"`
	// Domains is a list of domains authorized for use in the SDK.
	Domains []AuthorizedB2BDomain `json:"domains,omitempty"`
	// BundleIDs is a list of bundle IDs authorized for use in the SDK.
	BundleIDs []string `json:"bundle_ids,omitempty"`
}

type B2BConfig struct {
	// Basic: The basic configuration for the SDK. This includes enabling the SDK.
	Basic *B2BBasicConfig `json:"basic,omitempty"`
	// Sessions: The session configuration for the SDK.
	Sessions *B2BSessionsConfig `json:"sessions,omitempty"`
	// MagicLinks: The magic links configuration for the SDK.
	MagicLinks *B2BMagicLinksConfig `json:"magic_links,omitempty"`
	// OAuth: The OAuth configuration for the SDK.
	OAuth *B2BOAuthConfig `json:"oauth,omitempty"`
	// TOTPs is the TOTPs configuration for the SDK.
	TOTPs *B2BTOTPsConfig `json:"totps,omitempty"`
	// SSO is the SSO configuration for the B2B project SDK.
	SSO *B2BSSOConfig `json:"sso,omitempty"`
	// OTPs is the OTPs configuration for the SDK.
	OTPs *B2BOTPsConfig `json:"otps,omitempty"`
	// DFPPA is the Device Fingerprinting Protected Auth configuration for the SDK.
	DFPPA *B2BDFPPAConfig `json:"dfppa,omitempty"`
	// Passwords is the passwords configuration for the SDK.
	Passwords *B2BPasswordsConfig `json:"passwords,omitempty"`
	// Cookies is the cookies configuration for the SDK.
	Cookies *B2BCookiesConfig `json:"cookies,omitempty"`
}

type B2BCookiesConfig struct {
	// HTTPOnly: Specifies whether cookies should be set with the HttpOnly flag.
	HTTPOnly string `json:"http_only,omitempty"`
}

type B2BDFPPAConfig struct {
	// Enabled: Indicates whether Device Fingerprinting Protected Auth endpoints are enabled in the SDK.
	Enabled DFPPASetting `json:"enabled,omitempty"`
	// OnChallenge is the action to take when a DFPPA "challenge" verdict is returned.
	OnChallenge DFPPAOnChallengeAction `json:"on_challenge,omitempty"`
}

type B2BMagicLinksConfig struct {
	// Enabled: Indicates whether Magic Links endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// PKCERequired: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequired bool `json:"pkce_required,omitempty"`
}

type B2BOAuthConfig struct {
	// Enabled: Indicates whether OAuth endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// PKCERequired: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequired bool `json:"pkce_required,omitempty"`
}

type B2BOTPsConfig struct {
	// SMSEnabled indicates whether the SMS OTP endpoints are enabled in the SDK.
	SMSEnabled bool `json:"sms_enabled,omitempty"`
	// SMSAutofillMetadata is a list of metadata that can be used for autofill of SMS OTPs.
	SMSAutofillMetadata []SMSAutofillMetadata `json:"sms_autofill_metadata,omitempty"`
	// EmailEnabled indicates whether the email OTP endpoints are enabled in the SDK.
	EmailEnabled bool `json:"email_enabled,omitempty"`
}

type B2BPasswordsConfig struct {
	// Enabled: Indicates whether Passwords endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// PKCERequiredForPasswordResets: PKCERequired indicates whether PKCE is required for password resets. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequiredForPasswordResets bool `json:"pkce_required_for_password_resets,omitempty"`
}

type B2BSSOConfig struct {
	// Enabled: Indicates whether SSO endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// PKCERequired: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequired bool `json:"pkce_required,omitempty"`
}

type B2BSessionsConfig struct {
	// MaxSessionDurationMinutes is the maximum session duration that can be created in minutes.
	MaxSessionDurationMinutes int `json:"max_session_duration_minutes,omitempty"`
}

type B2BTOTPsConfig struct {
	// CreateTOTPs indicates whether TOTP creation is enabled in the SDK.
	CreateTOTPs bool `json:"create_totps,omitempty"`
	// Enabled: Indicates whether TOTP endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
}

type ConsumerBasicConfig struct {
	// Enabled indicates whether the consumer project SDK is enabled. This allows the SDK to manage user and
	// session data.
	Enabled bool `json:"enabled,omitempty"`
	// Domains is a list of domains authorized for use in the SDK.
	Domains []string `json:"domains,omitempty"`
	// BundleIDs is a list of bundle IDs authorized for use in the SDK.
	BundleIDs []string `json:"bundle_ids,omitempty"`
}

type ConsumerBiometricsConfig struct {
	// CreateBiometricsEnabled indicates whether biometrics creation is enabled in the SDK.
	CreateBiometricsEnabled bool `json:"create_biometrics_enabled,omitempty"`
	// Enabled indicates whether the consumer project SDK is enabled. This allows the SDK to manage user and
	// session data.
	Enabled bool `json:"enabled,omitempty"`
}

type ConsumerConfig struct {
	// Basic: The basic configuration for the SDK. This includes enabling the SDK.
	Basic *ConsumerBasicConfig `json:"basic,omitempty"`
	// Sessions: The session configuration for the SDK.
	Sessions *ConsumerSessionsConfig `json:"sessions,omitempty"`
	// MagicLinks: The magic links configuration for the SDK.
	MagicLinks *ConsumerMagicLinksConfig `json:"magic_links,omitempty"`
	// OTPs is the OTPs configuration for the SDK.
	OTPs *ConsumerOTPsConfig `json:"otps,omitempty"`
	// OAuth: The OAuth configuration for the SDK.
	OAuth *ConsumerOAuthConfig `json:"oauth,omitempty"`
	// TOTPs is the TOTPs configuration for the SDK.
	TOTPs *ConsumerTOTPsConfig `json:"totps,omitempty"`
	// WebAuthn is the WebAuthn configuration for the SDK.
	WebAuthn *ConsumerWebAuthnConfig `json:"webauthn,omitempty"`
	// CryptoWallets is the Crypto Wallets configuration for the SDK.
	CryptoWallets *ConsumerCryptoWalletsConfig `json:"crypto_wallets,omitempty"`
	// DFPPA is the Device Fingerprinting Protected Auth configuration for the SDK.
	DFPPA *ConsumerDFPPAConfig `json:"dfppa,omitempty"`
	// Biometrics is the biometrics configuration for the SDK.
	Biometrics *ConsumerBiometricsConfig `json:"biometrics,omitempty"`
	// Passwords is the passwords configuration for the SDK.
	Passwords *ConsumerPasswordsConfig `json:"passwords,omitempty"`
	// Cookies is the cookies configuration for the SDK.
	Cookies *ConsumerCookiesConfig `json:"cookies,omitempty"`
}

type ConsumerCookiesConfig struct {
	// HTTPOnly: Specifies whether cookies should be set with the HttpOnly flag.
	HTTPOnly string `json:"http_only,omitempty"`
}

type ConsumerCryptoWalletsConfig struct {
	// Enabled: Indicates whether Crypto Wallets endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// SIWERequired indicates whether Sign In With Ethereum is required for Crypto Wallets.
	SIWERequired bool `json:"siwe_required,omitempty"`
}

type ConsumerDFPPAConfig struct {
	// Enabled: Indicates whether Device Fingerprinting Protected Auth endpoints are enabled in the SDK.
	Enabled DFPPASetting `json:"enabled,omitempty"`
	// OnChallenge is the action to take when a DFPPA "challenge" verdict is returned.
	OnChallenge DFPPAOnChallengeAction `json:"on_challenge,omitempty"`
}

type ConsumerMagicLinksConfig struct {
	// LoginOrCreateEnabled indicates whether login-or-create with magic links is enabled in the SDK.
	LoginOrCreateEnabled bool `json:"login_or_create_enabled,omitempty"`
	// SendEnabled indicates whether the magic links send endpoint is enabled in the SDK.
	SendEnabled bool `json:"send_enabled,omitempty"`
	// PKCERequired: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequired bool `json:"pkce_required,omitempty"`
}

type ConsumerOAuthConfig struct {
	// Enabled: Indicates whether OAuth endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// PKCERequired: Indicates that PKCE is required in auth flows for the related SDK endpoints. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequired bool `json:"pkce_required,omitempty"`
}

type ConsumerOTPsConfig struct {
	// SMSLoginOrCreateEnabled indicates whether the SMS OTP login or create endpoint is enabled in the SDK.
	SMSLoginOrCreateEnabled bool `json:"sms_login_or_create_enabled,omitempty"`
	// WhatsAppLoginOrCreateEnabled indicates whether the WhatsApp OTP login or create endpoint is enabled in
	// the SDK.
	WhatsAppLoginOrCreateEnabled bool `json:"whatsapp_login_or_create_enabled,omitempty"`
	// EmailLoginOrCreateEnabled indicates whether the email OTP login or create endpoint is enabled in the SDK.
	EmailLoginOrCreateEnabled bool `json:"email_login_or_create_enabled,omitempty"`
	// SMSSendEnabled indicates whether the SMS OTP send endpoint is enabled in the SDK.
	SMSSendEnabled bool `json:"sms_send_enabled,omitempty"`
	// WhatsAppSendEnabled indicates whether the WhatsApp OTP send endpoint is enabled in the SDK.
	WhatsAppSendEnabled bool `json:"whatsapp_send_enabled,omitempty"`
	// EmailSendEnabled indicates whether the email OTP send endpoint is enabled in the SDK.
	EmailSendEnabled bool `json:"email_send_enabled,omitempty"`
	// SMSAutofillMetadata is a list of metadata that can be used for autofill of SMS OTPs.
	SMSAutofillMetadata []SMSAutofillMetadata `json:"sms_autofill_metadata,omitempty"`
}

type ConsumerPasswordsConfig struct {
	// Enabled: Indicates whether Passwords endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
	// PKCERequiredForPasswordResets: PKCERequired indicates whether PKCE is required for password resets. PKCE
	// increases security by introducing a one-time secret for each auth flow to ensure the user starts and
	// completes each auth flow from the same application on the device. This prevents a malicious app from
	// intercepting a redirect and authenticating with the user's token. PKCE is enabled by default for mobile
	// SDKs.
	PKCERequiredForPasswordResets bool `json:"pkce_required_for_password_resets,omitempty"`
}

type ConsumerSessionsConfig struct {
	// MaxSessionDurationMinutes is the maximum session duration that can be created in minutes.
	MaxSessionDurationMinutes int `json:"max_session_duration_minutes,omitempty"`
}

type ConsumerTOTPsConfig struct {
	// CreateTOTPs indicates whether TOTP creation is enabled in the SDK.
	CreateTOTPs bool `json:"create_totps,omitempty"`
	// Enabled: Indicates whether TOTP endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
}

type ConsumerWebAuthnConfig struct {
	CreateWebAuthns bool `json:"create_webauthn_s,omitempty"`
	// Enabled: Indicates whether WebAuthn endpoints are enabled in the SDK.
	Enabled bool `json:"enabled,omitempty"`
}

type SMSAutofillMetadata struct {
	// MetadataType is the type of metadata to use for autofill. This should be either "domain" or "hash".
	MetadataType SMSAutofillMetadataMetadataType `json:"metadata_type,omitempty"`
	// MetadataValue is the value of the metadata to use for autofill. This should be the associated domain
	// name (for MetadataType "domain") or application hash (for MetadataType "hash").
	MetadataValue string `json:"metadata_value,omitempty"`
	// BundleID is the ID of the bundle to use for autofill. This should be the associated bundle ID.
	BundleID string `json:"bundle_id,omitempty"`
	// ID is the unique identifier for the trusted token profile.
	ID int `json:"id,omitempty"`
}

// GetB2BConfigRequest: Request type for `SDK.GetB2BConfig`.
type GetB2BConfigRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// GetB2BConfigResponse: Response type for `SDK.GetB2BConfig`.
type GetB2BConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the SDK configuration.
	Config B2BConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetConsumerConfigRequest: Request type for `SDK.GetConsumerConfig`.
type GetConsumerConfigRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// GetConsumerConfigResponse: Response type for `SDK.GetConsumerConfig`.
type GetConsumerConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the SDK configuration.
	Config ConsumerConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetB2BConfigRequest: Request type for `SDK.SetB2BConfig`.
type SetB2BConfigRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// Config is the SDK configuration.
	Config *B2BConfig `json:"config,omitempty"`
}

// SetB2BConfigResponse: Response type for `SDK.SetB2BConfig`.
type SetB2BConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the SDK configuration.
	Config B2BConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetConsumerConfigRequest: Request type for `SDK.SetConsumerConfig`.
type SetConsumerConfigRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// Config is the SDK configuration.
	Config *ConsumerConfig `json:"config,omitempty"`
}

// SetConsumerConfigResponse: Response type for `SDK.SetConsumerConfig`.
type SetConsumerConfigResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Config is the SDK configuration.
	Config ConsumerConfig `json:"config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type DFPPAOnChallengeAction string

const (
	DFPPAOnChallengeActionUnknown        DFPPAOnChallengeAction = "UNKNOWN_DFPPA_ON_CHALLENGE_ACTION"
	DFPPAOnChallengeActionAllow          DFPPAOnChallengeAction = "ALLOW"
	DFPPAOnChallengeActionBlock          DFPPAOnChallengeAction = "BLOCK"
	DFPPAOnChallengeActionTriggerCaptcha DFPPAOnChallengeAction = "TRIGGER_CAPTCHA"
)

func DFPPAOnChallengeActions() []DFPPAOnChallengeAction {
	return []DFPPAOnChallengeAction{
		DFPPAOnChallengeActionAllow,
		DFPPAOnChallengeActionBlock,
		DFPPAOnChallengeActionTriggerCaptcha,
	}
}

type DFPPASetting string

const (
	DFPPASettingUnknown  DFPPASetting = "UNKNOWN_DFPPA_SETTING"
	DFPPASettingEnabled  DFPPASetting = "ENABLED"
	DFPPASettingPassive  DFPPASetting = "PASSIVE"
	DFPPASettingDisabled DFPPASetting = "DISABLED"
)

func DFPPASettings() []DFPPASetting {
	return []DFPPASetting{
		DFPPASettingEnabled,
		DFPPASettingPassive,
		DFPPASettingDisabled,
	}
}

type SMSAutofillMetadataMetadataType string

const (
	SMSAutofillMetadataMetadataTypeDomain SMSAutofillMetadataMetadataType = "domain"
	SMSAutofillMetadataMetadataTypeHash   SMSAutofillMetadataMetadataType = "hash"
)

func SMSAutofillMetadataMetadataTypes() []SMSAutofillMetadataMetadataType {
	return []SMSAutofillMetadataMetadataType{
		SMSAutofillMetadataMetadataTypeHash,
	}
}
