package rbacpolicy

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type DefaultRole struct {
	Permissions []Permission `json:"permissions,omitempty"`
}
type Permission struct {
	ResourceID string   `json:"resource_id,omitempty"`
	Actions    []string `json:"actions,omitempty"`
}
type Policy struct {
	StytchResources []Resource   `json:"stytch_resources,omitempty"`
	CustomRoles     []Role       `json:"custom_roles,omitempty"`
	CustomResources []Resource   `json:"custom_resources,omitempty"`
	CustomScopes    []Scope      `json:"custom_scopes,omitempty"`
	StytchMember    *DefaultRole `json:"stytch_member,omitempty"`
	StytchAdmin     *DefaultRole `json:"stytch_admin,omitempty"`
	StytchUser      *DefaultRole `json:"stytch_user,omitempty"`
}
type Resource struct {
	ResourceID       string   `json:"resource_id,omitempty"`
	Description      string   `json:"description,omitempty"`
	AvailableActions []string `json:"available_actions,omitempty"`
}
type Role struct {
	RoleID      string       `json:"role_id,omitempty"`
	Description string       `json:"description,omitempty"`
	Permissions []Permission `json:"permissions,omitempty"`
}
type Scope struct {
	Scope       string       `json:"scope,omitempty"`
	Description string       `json:"description,omitempty"`
	Permissions []Permission `json:"permissions,omitempty"`
}

// GetRequest: Request type for `RBACPolicy.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve the RBAC policy.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve the RBAC policy.
	EnvironmentSlug string `json:"-"`
}

// GetResponse: Response type for `RBACPolicy.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Policy is the RBAC policy for the environment.
	Policy Policy `json:"policy,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetRequest: Request type for `RBACPolicy.Set`.
type SetRequest struct {
	// ProjectSlug is the slug of the project for which to set the RBAC policy.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to set the RBAC policy.
	EnvironmentSlug string `json:"-"`
	// StytchMember: The following fields are valid for B2B projects only: StytchMember is the default role
	// given to members within the environment. Only permissions are returned; role_id and description are
	// managed by Stytch.
	StytchMember *DefaultRole `json:"stytch_member,omitempty"`
	// StytchAdmin is the role assigned to admins within an organization. Only permissions are returned;
	// role_id and description are managed by Stytch.
	StytchAdmin *DefaultRole `json:"stytch_admin,omitempty"`
	// StytchUser: The following field is valid for Consumer projects only: StytchUser is the default role
	// given to users within the environment. Only permissions are returned; role_id and description are
	// managed by Stytch.
	StytchUser *DefaultRole `json:"stytch_user,omitempty"`
	// CustomRoles: The following fields are valid for both B2B and Consumer projects: CustomRoles are
	// additional roles that exist within the environment beyond the stytch_member, stytch_admin, or
	// stytch_user roles.
	CustomRoles []*Role `json:"custom_roles,omitempty"`
	// CustomResources are resources that exist within the environment beyond those defined within the
	// stytch_resources.
	CustomResources []*Resource `json:"custom_resources,omitempty"`
	// CustomScopes are additional scopes that exist within the environment beyond those defined by default.
	CustomScopes []*Scope `json:"custom_scopes,omitempty"`
}

// SetResponse: Response type for `RBACPolicy.Set`.
type SetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Policy is the RBAC policy for the environment.
	Policy Policy `json:"policy,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}
