package redirecturls

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type RedirectURL struct {
	// URL: The URL to which to redirect.
	URL string `json:"url,omitempty"`
	// ValidTypes is a list of all the URLRedirectType available for this URL.
	ValidTypes []URLType `json:"valid_types,omitempty"`
}

type URLType struct {
	// IsDefault is true if this is the default redirect type, false otherwise.
	IsDefault bool `json:"is_default,omitempty"`
	// Type: One of the RedirectType values.
	Type RedirectURLType `json:"type,omitempty"`
}

// CreateRequest: Request type for `RedirectURLs.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// URL: The URL to which to redirect.
	URL string `json:"url,omitempty"`
	// ValidTypes is a list of all the URLRedirectType available for this URL.
	ValidTypes []URLType `json:"valid_types,omitempty"`
	// DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no
	// other RedirectURL exists for the given type. This is primarily intended for use with
	// stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create
	// request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL
	// exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is
	// possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no
	// default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic
	// link), you will need to explicitly specify which redirect URL should be used.
	DoNotPromoteDefaults *bool `json:"do_not_promote_defaults,omitempty"`
}

// CreateResponse: Response type for `RedirectURLs.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// RedirectURL is the object that was created.
	RedirectURL RedirectURL `json:"redirect_url,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `RedirectURLs.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// URL: The URL to which to redirect.
	URL string `json:"-"`
	// DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no
	// other RedirectURL exists for the given type. This is primarily intended for use with
	// stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create
	// request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL
	// exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is
	// possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no
	// default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic
	// link), you will need to explicitly specify which redirect URL should be used.
	DoNotPromoteDefaults *bool `json:"-"`
}

// DeleteResponse: Response type for `RedirectURLs.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `RedirectURLs.GetAll`.
type GetAllRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// GetAllResponse: Response type for `RedirectURLs.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// RedirectURLs is a list of all the redirect URLs for the project.
	RedirectURLs []RedirectURL `json:"redirect_urls,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `RedirectURLs.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// URL: The URL to which to redirect.
	URL string `json:"-"`
}

// GetResponse: Response type for `RedirectURLs.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// RedirectURL is the redirect URL.
	RedirectURL RedirectURL `json:"redirect_url,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `RedirectURLs.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// URL: The URL to which to redirect.
	URL string `json:"-"`
	// ValidTypes is a list of all the URLRedirectType available for this URL.
	ValidTypes []URLType `json:"valid_types,omitempty"`
	// DoNotPromoteDefaults is used to suppress the automatic "promotion" of a RedirectURL to the default if no
	// other RedirectURL exists for the given type. This is primarily intended for use with
	// stytchauth/terraform-provider-stytch to allow Terraform provisioning to be idempotent. For a Create
	// request, the default behavior is to promote the RedirectURL to the default if no other RedirectURL
	// exists for the given type, even if `IsDefault` was set to false.  WARNING: If this is set to true, it is
	// possible to have valid RedirectURLs for a given type but *no* default RedirectURL for that type. If no
	// default exists for a given type, using an API endpoint that uses redirect URLs (such as sending a magic
	// link), you will need to explicitly specify which redirect URL should be used.
	DoNotPromoteDefaults *bool `json:"do_not_promote_defaults,omitempty"`
}

// UpdateResponse: Response type for `RedirectURLs.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// RedirectURL is the object that was updated.
	RedirectURL RedirectURL `json:"redirect_url,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type RedirectURLType string

const (
	RedirectURLTypeUnknown       RedirectURLType = "UNKNOWN_REDIRECT_TYPE"
	RedirectURLTypeLogin         RedirectURLType = "LOGIN"
	RedirectURLTypeInvite        RedirectURLType = "INVITE"
	RedirectURLTypeSignup        RedirectURLType = "SIGNUP"
	RedirectURLTypeResetPassword RedirectURLType = "RESET_PASSWORD"
	RedirectURLTypeDiscovery     RedirectURLType = "DISCOVERY"
)

func RedirectURLTypes() []RedirectURLType {
	return []RedirectURLType{
		RedirectURLTypeLogin,
		RedirectURLTypeInvite,
		RedirectURLTypeSignup,
		RedirectURLTypeResetPassword,
		RedirectURLTypeDiscovery,
	}
}
