package trustedtokenprofiles

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

// PEMFile:
type PEMFile struct {
	// PEMFileID is the unique identifier for the PEM file.
	PEMFileID string `json:"pem_file_id,omitempty"`
	// PublicKey is the public key content.
	PublicKey string `json:"public_key,omitempty"`
}

// TrustedTokenProfile:
type TrustedTokenProfile struct {
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"profile_id,omitempty"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name string `json:"name,omitempty"`
	// Audience is the audience for the trusted token profile.
	Audience string `json:"audience,omitempty"`
	// Issuer is the issuer for the trusted token profile.
	Issuer string `json:"issuer,omitempty"`
	// PEMFiles is a list of PEM files.
	PEMFiles []PEMFile `json:"pem_files,omitempty"`
	// CanJITProvision indicates whether the trusted token profile can be provisioned JIT.
	CanJITProvision bool `json:"can_jit_provision,omitempty"`
	// JWKSURL: JwksURL is the JWKS URL for the trusted token profile.
	JWKSURL *string `json:"jwks_url,omitempty"`
	// AttributeMapping is the attribute mapping for the trusted token profile.
	AttributeMapping *map[string]any `json:"attribute_mapping,omitempty"`
	// PublicKeyType is the type of public key.
	PublicKeyType PublicKeyType `json:"public_key_type,omitempty"`
}

// CreatePEMFileRequest: Request type for `TrustedTokenProfiles.CreatePEMFile`.
type CreatePEMFileRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"-"`
	// PublicKey is the public key content.
	PublicKey string `json:"public_key,omitempty"`
}

// CreatePEMFileResponse: Response type for `TrustedTokenProfiles.CreatePEMFile`.
type CreatePEMFileResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PEMFile is the PEM file that was created.
	PEMFile PEMFile `json:"pem_file,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// CreateRequest: Request type for `TrustedTokenProfiles.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name string `json:"name,omitempty"`
	// Audience is the audience for the trusted token profile.
	Audience string `json:"audience,omitempty"`
	// Issuer is the issuer for the trusted token profile.
	Issuer string `json:"issuer,omitempty"`
	// PEMFiles is a list of PEM files.
	PEMFiles []string `json:"pem_files,omitempty"`
	// CanJITProvision indicates whether the trusted token profile can be provisioned JIT.
	CanJITProvision bool `json:"can_jit_provision,omitempty"`
	// JWKSURL: JwksURL is the JWKS URL for the trusted token profile.
	JWKSURL *string `json:"jwks_url,omitempty"`
	// AttributeMapping is the attribute mapping for the trusted token profile.
	AttributeMapping *map[string]any `json:"attribute_mapping,omitempty"`
	// PublicKeyType is the type of public key.
	PublicKeyType PublicKeyType `json:"public_key_type,omitempty"`
}

// CreateResponse: Response type for `TrustedTokenProfiles.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Profile: TrustedTokenProfile is the trusted token profile that was created.
	Profile TrustedTokenProfile `json:"profile,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeletePEMFileRequest: Request type for `TrustedTokenProfiles.DeletePEMFile`.
type DeletePEMFileRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"-"`
	// PEMFileID is the unique identifier for the PEM file.
	PEMFileID string `json:"-"`
}

// DeletePEMFileResponse: Response type for `TrustedTokenProfiles.DeletePEMFile`.
type DeletePEMFileResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `TrustedTokenProfiles.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"-"`
}

// DeleteResponse: Response type for `TrustedTokenProfiles.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `TrustedTokenProfiles.GetAll`.
type GetAllRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// GetAllResponse: Response type for `TrustedTokenProfiles.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string                `json:"request_id,omitempty"`
	Profiles  []TrustedTokenProfile `json:"profiles,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetPEMFileRequest: Request type for `TrustedTokenProfiles.GetPEMFile`.
type GetPEMFileRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"-"`
	// PEMFileID is the unique identifier for the PEM file.
	PEMFileID string `json:"-"`
}

// GetPEMFileResponse: Response type for `TrustedTokenProfiles.GetPEMFile`.
type GetPEMFileResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PEMFile is the PEM file that was retrieved.
	PEMFile PEMFile `json:"pem_file,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `TrustedTokenProfiles.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"-"`
}

// GetResponse: Response type for `TrustedTokenProfiles.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Profile: TrustedTokenProfile is the trusted token profile.
	Profile TrustedTokenProfile `json:"profile,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `TrustedTokenProfiles.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// ProfileID is the unique identifier for the trusted token profile.
	ProfileID string `json:"-"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name *string `json:"name,omitempty"`
	// Audience is the audience for the trusted token profile.
	Audience *string `json:"audience,omitempty"`
	// Issuer is the issuer for the trusted token profile.
	Issuer *string `json:"issuer,omitempty"`
	// JWKSURL: JwksURL is the JWKS URL for the trusted token profile.
	JWKSURL *string `json:"jwks_url,omitempty"`
	// AttributeMapping is the attribute mapping for the trusted token profile.
	AttributeMapping *map[string]any `json:"attribute_mapping,omitempty"`
	// CanJITProvision indicates whether the trusted token profile can be provisioned JIT.
	CanJITProvision *bool `json:"can_jit_provision,omitempty"`
}

// UpdateResponse: Response type for `TrustedTokenProfiles.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Profile: TrustedTokenProfile is the trusted token profile that was updated.
	Profile TrustedTokenProfile `json:"profile,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type PublicKeyType string

const (
	PublicKeyTypeUnspecified PublicKeyType = "UNSPECIFIED"
	PublicKeyTypeJwk         PublicKeyType = "JWK"
	PublicKeyTypePem         PublicKeyType = "PEM"
)

func PublicKeyTypes() []PublicKeyType {
	return []PublicKeyType{
		PublicKeyTypeJwk,
		PublicKeyTypePem,
	}
}
