package countrycodeallowlist

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

// GetAllowedSMSCountryCodesRequest: Request type for `CountryCodeAllowlist.GetAllowedSMSCountryCodes`.
type GetAllowedSMSCountryCodesRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetAllowedSMSCountryCodesResponse: Response type for `CountryCodeAllowlist.GetAllowedSMSCountryCodes`.
type GetAllowedSMSCountryCodesResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// CountryCodes is a list of country codes that are allowed for SMS.
	CountryCodes []string `json:"country_codes,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllowedWhatsAppCountryCodesRequest: Request type for
// `CountryCodeAllowlist.GetAllowedWhatsAppCountryCodes`.
type GetAllowedWhatsAppCountryCodesRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetAllowedWhatsAppCountryCodesResponse: Response type for
// `CountryCodeAllowlist.GetAllowedWhatsAppCountryCodes`.
type GetAllowedWhatsAppCountryCodesResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// CountryCodes is a list of country codes that are allowed for SMS.
	CountryCodes []string `json:"country_codes,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetAllowedSMSCountryCodesRequest: Request type for `CountryCodeAllowlist.SetAllowedSMSCountryCodes`.
type SetAllowedSMSCountryCodesRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// CountryCodes is a list of country codes that are allowed for SMS.
	CountryCodes []string `json:"country_codes,omitempty"`
}

// SetAllowedSMSCountryCodesResponse: Response type for `CountryCodeAllowlist.SetAllowedSMSCountryCodes`.
type SetAllowedSMSCountryCodesResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// CountryCodes is a list of country codes that are allowed for SMS.
	CountryCodes []string `json:"country_codes,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetAllowedWhatsAppCountryCodesRequest: Request type for
// `CountryCodeAllowlist.SetAllowedWhatsAppCountryCodes`.
type SetAllowedWhatsAppCountryCodesRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// CountryCodes is a list of country codes that are allowed for SMS.
	CountryCodes []string `json:"country_codes,omitempty"`
}

// SetAllowedWhatsAppCountryCodesResponse: Response type for
// `CountryCodeAllowlist.SetAllowedWhatsAppCountryCodes`.
type SetAllowedWhatsAppCountryCodesResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// CountryCodes is a list of country codes that are allowed for SMS.
	CountryCodes []string `json:"country_codes,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}
