package secrets

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import "time"

type MaskedSecret struct {
	SecretID  string    `json:"secret_id,omitempty"`
	LastFour  string    `json:"last_four,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UsedAt    time.Time `json:"used_at,omitempty"`
}
type Secret struct {
	SecretID  string    `json:"secret_id,omitempty"`
	Secret    string    `json:"secret,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// CreateRequest: Request type for `Secrets.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project for which to create the secret.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to create the secret.
	EnvironmentSlug string `json:"-"`
}

// CreateResponse: Response type for `Secrets.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Secret is the secret value. This is only visible once upon secret creation.
	Secret Secret `json:"secret,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `Secrets.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project for which to delete the secret.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to delete the secret.
	EnvironmentSlug string `json:"-"`
	// SecretID is the ID of the secret to delete.
	SecretID string `json:"-"`
}

// DeleteResponse: Response type for `Secrets.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `Secrets.GetAll`.
type GetAllRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve the secrets.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve the secrets.
	EnvironmentSlug string `json:"-"`
}

// GetAllResponse: Response type for `Secrets.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Secrets is all the secrets that belong to the project.
	Secrets []MaskedSecret `json:"secrets,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `Secrets.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve the secret.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve the secret.
	EnvironmentSlug string `json:"-"`
	// SecretID is the ID of the secret to retrieve.
	SecretID string `json:"-"`
}

// GetResponse: Response type for `Secrets.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Secret is the secret value. This is only visible once upon secret creation.
	Secret MaskedSecret `json:"secret,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}
