package environments

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import "time"

// Environment:
type Environment struct {
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"environment_slug,omitempty"`
	ProjectSlug     string `json:"project_slug,omitempty"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name string `json:"name,omitempty"`
	// OAuthCallbackID: Configuration fields for the Environment are below. OAuthCallbackID is the callback ID
	// used in OAuth requests for the environment.
	OAuthCallbackID string `json:"oauth_callback_id,omitempty"`
	// CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
	CrossOrgPasswordsEnabled bool `json:"cross_org_passwords_enabled,omitempty"`
	// UserImpersonationEnabled indicates whether user impersonation is enabled for the environment.
	UserImpersonationEnabled bool `json:"user_impersonation_enabled,omitempty"`
	// ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
	ZeroDowntimeSessionMigrationURL string `json:"zero_downtime_session_migration_url,omitempty"`
	// UserLockSelfServeEnabled: User locking fields. UserLockSelfServeEnabled indicates whether users in the
	// environment who get locked out should automatically get an unlock email magic link.
	UserLockSelfServeEnabled bool `json:"user_lock_self_serve_enabled,omitempty"`
	// UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
	// environment to be locked. Defaults to 10.
	UserLockThreshold int `json:"user_lock_threshold,omitempty"`
	// UserLockTTL represents the time in seconds that the user in the environment remains locked once the lock
	// is set. Defaults to 1 hour (3600 seconds).
	UserLockTTL int `json:"user_lock_ttl,omitempty"`
	// IDPAuthorizationURL: IDP fields. IDPAuthorizationURL is the OpenID Configuration endpoint for Connected
	// Apps for the environment.
	IDPAuthorizationURL string `json:"idp_authorization_url,omitempty"`
	// IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client
	// Registration (DCR) for Connected Apps.
	IDPDynamicClientRegistrationEnabled bool `json:"idp_dynamic_client_registration_enabled,omitempty"`
	// IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients
	// created through Dynamic Client Registration (DCR).
	IDPDynamicClientRegistrationAccessTokenTemplateContent string `json:"idp_dynamic_client_registration_access_token_template_content,omitempty"`
	// Type is the environment's type. See EnvironmentTypes() for possible values.
	Type EnvironmentType `json:"type,omitempty"`
	// CreatedAt is the ISO-8601 timestamp for when the environment was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
}

// Metrics:
type Metrics struct {
	// UserCount is the number of active users in the environment (only relevant for Consumer projects).
	UserCount uint32 `json:"user_count,omitempty"`
	// OrganizationCount is the number of active organizations in the environment (only relevant for B2B
	// projects).
	OrganizationCount uint32 `json:"organization_count,omitempty"`
	// MemberCount is the number of active members in the environment (only relevant for B2B projects).
	MemberCount uint32 `json:"member_count,omitempty"`
	// M2MClientCount is the number of active M2M clients in the environment.
	M2MClientCount uint32 `json:"m2m_client_count,omitempty"`
}

// CreateRequest: Request type for `Environments.Create`.
type CreateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// Name is the name of the environment.
	Name string `json:"name,omitempty"`
	// Type is the environment's type. See EnvironmentTypes() for possible values.
	Type EnvironmentType `json:"type,omitempty"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug *string `json:"environment_slug,omitempty"`
	// CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
	CrossOrgPasswordsEnabled *bool `json:"cross_org_passwords_enabled,omitempty"`
	// UserImpersonationEnabled indicates whether user impersonation is enabled for the environment.
	UserImpersonationEnabled *bool `json:"user_impersonation_enabled,omitempty"`
	// ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
	ZeroDowntimeSessionMigrationURL *string `json:"zero_downtime_session_migration_url,omitempty"`
	// UserLockSelfServeEnabled: User locking fields. UserLockSelfServeEnabled indicates whether users in the
	// environment who get locked out should automatically get an unlock email magic link.
	UserLockSelfServeEnabled *bool `json:"user_lock_self_serve_enabled,omitempty"`
	// UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
	// environment to be locked. Defaults to 10.
	UserLockThreshold *int32 `json:"user_lock_threshold,omitempty"`
	// UserLockTTL represents the time in seconds that the user in the environment remains locked once the lock
	// is set. Defaults to 1 hour (3600 seconds).
	UserLockTTL *int32 `json:"user_lock_ttl,omitempty"`
	// IDPAuthorizationURL: IDP fields. IDPAuthorizationURL is the OpenID Configuration endpoint for Connected
	// Apps for the environment.
	IDPAuthorizationURL *string `json:"idp_authorization_url,omitempty"`
	// IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client
	// Registration (DCR) for Connected Apps.
	IDPDynamicClientRegistrationEnabled *bool `json:"idp_dynamic_client_registration_enabled,omitempty"`
	// IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients
	// created through Dynamic Client Registration (DCR).
	IDPDynamicClientRegistrationAccessTokenTemplateContent *string `json:"idp_dynamic_client_registration_access_token_template_content,omitempty"`
}

// CreateResponse: Response type for `Environments.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environment contains the details for the newly created environment.
	Environment Environment `json:"environment,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `Environments.Delete`.
type DeleteRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// DeleteResponse: Response type for `Environments.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `Environments.GetAll`.
type GetAllRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
}

// GetAllResponse: Response type for `Environments.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environments is the list of environments that belong to the specified project.
	Environments []Environment `json:"environments,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetMetricsRequest: Request type for `Environments.GetMetrics`.
type GetMetricsRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// GetMetricsResponse: Response type for `Environments.GetMetrics`.
type GetMetricsResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Metrics contains various metrics for the environment.
	Metrics Metrics `json:"metrics,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `Environments.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
}

// GetResponse: Response type for `Environments.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environment contains the environment details.
	Environment Environment `json:"environment,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `Environments.Update`.
type UpdateRequest struct {
	// ProjectSlug is the slug of the project.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment.
	EnvironmentSlug string `json:"-"`
	// Name is the name of the environment.
	Name *string `json:"name,omitempty"`
	// CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
	CrossOrgPasswordsEnabled *bool `json:"cross_org_passwords_enabled,omitempty"`
	// UserImpersonationEnabled indicates whether user impersonation is enabled for the environment.
	UserImpersonationEnabled *bool `json:"user_impersonation_enabled,omitempty"`
	// ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
	ZeroDowntimeSessionMigrationURL *string `json:"zero_downtime_session_migration_url,omitempty"`
	// UserLockSelfServeEnabled: User locking fields. UserLockSelfServeEnabled indicates whether users in the
	// environment who get locked out should automatically get an unlock email magic link.
	UserLockSelfServeEnabled *bool `json:"user_lock_self_serve_enabled,omitempty"`
	// UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
	// environment to be locked. Defaults to 10.
	UserLockThreshold *int32 `json:"user_lock_threshold,omitempty"`
	// UserLockTTL represents the time in seconds that the user in the environment remains locked once the lock
	// is set. Defaults to 1 hour (3600 seconds).
	UserLockTTL *int32 `json:"user_lock_ttl,omitempty"`
	// IDPAuthorizationURL: IDP fields. IDPAuthorizationURL is the OpenID Configuration endpoint for Connected
	// Apps for the environment.
	IDPAuthorizationURL *string `json:"idp_authorization_url,omitempty"`
	// IDPDynamicClientRegistrationEnabled indicates whether the project has opted in to Dynamic Client
	// Registration (DCR) for Connected Apps.
	IDPDynamicClientRegistrationEnabled *bool `json:"idp_dynamic_client_registration_enabled,omitempty"`
	// IDPDynamicClientRegistrationAccessTokenTemplateContent is the access token template to use for clients
	// created through Dynamic Client Registration (DCR).
	IDPDynamicClientRegistrationAccessTokenTemplateContent *string `json:"idp_dynamic_client_registration_access_token_template_content,omitempty"`
}

// UpdateResponse: Response type for `Environments.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environment contains the details for the updated environment.
	Environment Environment `json:"environment,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type EnvironmentType string

const (
	EnvironmentTypeUnknown EnvironmentType = "UNKNOWN_ENVIRONMENT_TYPE"
	EnvironmentTypeLive    EnvironmentType = "LIVE"
	EnvironmentTypeTest    EnvironmentType = "TEST"
)

func EnvironmentTypes() []EnvironmentType {
	return []EnvironmentType{
		EnvironmentTypeLive,
		EnvironmentTypeTest,
	}
}
