package environments

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

import "time"

type Environment struct {
	EnvironmentSlug                                        string          `json:"environment_slug,omitempty"`
	ProjectSlug                                            string          `json:"project_slug,omitempty"`
	Name                                                   string          `json:"name,omitempty"`
	OAuthCallbackID                                        string          `json:"oauth_callback_id,omitempty"`
	CrossOrgPasswordsEnabled                               bool            `json:"cross_org_passwords_enabled,omitempty"`
	UserImpersonationEnabled                               bool            `json:"user_impersonation_enabled,omitempty"`
	ZeroDowntimeSessionMigrationURL                        string          `json:"zero_downtime_session_migration_url,omitempty"`
	UserLockSelfServeEnabled                               bool            `json:"user_lock_self_serve_enabled,omitempty"`
	UserLockThreshold                                      int             `json:"user_lock_threshold,omitempty"`
	UserLockTtl                                            int             `json:"user_lock_ttl,omitempty"`
	IDPAuthorizationURL                                    string          `json:"idp_authorization_url,omitempty"`
	IDPDynamicClientRegistrationEnabled                    bool            `json:"idp_dynamic_client_registration_enabled,omitempty"`
	IDPDynamicClientRegistrationAccessTokenTemplateContent string          `json:"idp_dynamic_client_registration_access_token_template_content,omitempty"`
	Type                                                   EnvironmentType `json:"type,omitempty"`
	CreatedAt                                              time.Time       `json:"created_at,omitempty"`
}
type Metrics struct {
	UserCount         uint32 `json:"user_count,omitempty"`
	OrganizationCount uint32 `json:"organization_count,omitempty"`
	MemberCount       uint32 `json:"member_count,omitempty"`
	M2MClientCount    uint32 `json:"m2m_client_count,omitempty"`
}

// CreateRequest: Request type for `Environments.Create`.
type CreateRequest struct {
	ProjectSlug string `json:"-"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name string `json:"name,omitempty"`
	// Type is the environment's type. See EnvironmentTypes() for possible values.
	Type EnvironmentType `json:"type,omitempty"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug *string `json:"environment_slug,omitempty"`
	// CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
	CrossOrgPasswordsEnabled *bool `json:"cross_org_passwords_enabled,omitempty"`
	// UserImpersonationEnabled indicates whether user impersonation is enabled for the environment.
	UserImpersonationEnabled *bool `json:"user_impersonation_enabled,omitempty"`
	// ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
	ZeroDowntimeSessionMigrationURL *string `json:"zero_downtime_session_migration_url,omitempty"`
	// UserLockSelfServeEnabled: User locking fields. UserLockSelfServeEnabled indicates whether users in the
	// environment who get locked out should automatically get an unlock email magic link.
	UserLockSelfServeEnabled *bool `json:"user_lock_self_serve_enabled,omitempty"`
	// UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
	// environment to be locked. Defaults to 10.
	UserLockThreshold                                      *int32  `json:"user_lock_threshold,omitempty"`
	UserLockTtl                                            *int32  `json:"user_lock_ttl,omitempty"`
	IDPAuthorizationURL                                    *string `json:"idp_authorization_url,omitempty"`
	IDPDynamicClientRegistrationEnabled                    *bool   `json:"idp_dynamic_client_registration_enabled,omitempty"`
	IDPDynamicClientRegistrationAccessTokenTemplateContent *string `json:"idp_dynamic_client_registration_access_token_template_content,omitempty"`
}

// CreateResponse: Response type for `Environments.Create`.
type CreateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environment contains the details for the newly created environment.
	Environment Environment `json:"environment,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// DeleteRequest: Request type for `Environments.Delete`.
type DeleteRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// DeleteResponse: Response type for `Environments.Delete`.
type DeleteResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetAllRequest: Request type for `Environments.GetAll`.
type GetAllRequest struct {
	ProjectSlug string `json:"-"`
}

// GetAllResponse: Response type for `Environments.GetAll`.
type GetAllResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environments is the list of environments that belong to the specified project.
	Environments []Environment `json:"environments,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetMetricsRequest: Request type for `Environments.GetMetrics`.
type GetMetricsRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetMetricsResponse: Response type for `Environments.GetMetrics`.
type GetMetricsResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Metrics contains various metrics for the environment.
	Metrics Metrics `json:"metrics,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// GetRequest: Request type for `Environments.Get`.
type GetRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
}

// GetResponse: Response type for `Environments.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environment contains the details for the newly created environment.
	Environment Environment `json:"environment,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// UpdateRequest: Request type for `Environments.Update`.
type UpdateRequest struct {
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve allowed SMS country codes.
	EnvironmentSlug string `json:"-"`
	// Name is a human-readable name of the template. This does not have to be unique.
	Name *string `json:"name,omitempty"`
	// CrossOrgPasswordsEnabled indicates whether the environment uses cross-org passwords.
	CrossOrgPasswordsEnabled *bool `json:"cross_org_passwords_enabled,omitempty"`
	// UserImpersonationEnabled indicates whether user impersonation is enabled for the environment.
	UserImpersonationEnabled *bool `json:"user_impersonation_enabled,omitempty"`
	// ZeroDowntimeSessionMigrationURL is the OIDC-compliant UserInfo endpoint for session migration.
	ZeroDowntimeSessionMigrationURL *string `json:"zero_downtime_session_migration_url,omitempty"`
	// UserLockSelfServeEnabled: User locking fields. UserLockSelfServeEnabled indicates whether users in the
	// environment who get locked out should automatically get an unlock email magic link.
	UserLockSelfServeEnabled *bool `json:"user_lock_self_serve_enabled,omitempty"`
	// UserLockThreshold represents the number of failed authenticate attempts that will cause a user in the
	// environment to be locked. Defaults to 10.
	UserLockThreshold                                      *int32  `json:"user_lock_threshold,omitempty"`
	UserLockTtl                                            *int32  `json:"user_lock_ttl,omitempty"`
	IDPAuthorizationURL                                    *string `json:"idp_authorization_url,omitempty"`
	IDPDynamicClientRegistrationEnabled                    *bool   `json:"idp_dynamic_client_registration_enabled,omitempty"`
	IDPDynamicClientRegistrationAccessTokenTemplateContent *string `json:"idp_dynamic_client_registration_access_token_template_content,omitempty"`
}

// UpdateResponse: Response type for `Environments.Update`.
type UpdateResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// Environment contains the details for the newly created environment.
	Environment Environment `json:"environment,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type EnvironmentType string

const (
	EnvironmentTypeUnknown EnvironmentType = "UNKNOWN_ENVIRONMENT_TYPE"
	EnvironmentTypeLive    EnvironmentType = "LIVE"
	EnvironmentTypeTest    EnvironmentType = "TEST"
)

func EnvironmentTypes() []EnvironmentType {
	return []EnvironmentType{
		EnvironmentTypeLive,
		EnvironmentTypeTest,
	}
}
