name: Build
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true

      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.59
          args: --timeout 5m

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go:
          # Start at the `go` directive version in go.mod.
          - "1.18"
          # And test the latest Go release
          - "1.22"

    env:
      STYTCH_WORKSPACE_KEY_ID: ${{ secrets.STYTCH_WORKSPACE_KEY_ID }}
      STYTCH_WORKSPACE_KEY_SECRET: ${{ secrets.STYTCH_WORKSPACE_KEY_SECRET }}
      STYTCH_WORKSPACE_BASE_URI: ${{ secrets.STYTCH_WORKSPACE_BASE_URI }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - run: go test ./...
