package passwordstrengthconfig

// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

type PasswordStrengthConfig struct {
	CheckBreachOnCreation       bool             `json:"check_breach_on_creation,omitempty"`
	CheckBreachOnAuthentication bool             `json:"check_breach_on_authentication,omitempty"`
	ValidateOnAuthentication    bool             `json:"validate_on_authentication,omitempty"`
	ValidationPolicy            ValidationPolicy `json:"validation_policy,omitempty"`
	LudsMinPasswordLength       *int32           `json:"luds_min_password_length,omitempty"`
	LudsMinPasswordComplexity   *int32           `json:"luds_min_password_complexity,omitempty"`
}

// GetRequest: Request type for `PasswordStrengthConfig.Get`.
type GetRequest struct {
	// ProjectSlug is the slug of the project for which to retrieve the password strength config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to retrieve the password strength config.
	EnvironmentSlug string `json:"-"`
}

// GetResponse: Response type for `PasswordStrengthConfig.Get`.
type GetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PasswordStrengthConfig is the password strength configuration for the environment.
	PasswordStrengthConfig PasswordStrengthConfig `json:"password_strength_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

// SetRequest: Request type for `PasswordStrengthConfig.Set`.
type SetRequest struct {
	// ProjectSlug is the slug of the project for which to set the password strength config.
	ProjectSlug string `json:"-"`
	// EnvironmentSlug is the slug of the environment for which to set the password strength config.
	EnvironmentSlug string `json:"-"`
	// CheckBreachOnCreation is a flag to check whether to use the HaveIBeenPwned database to detect password
	// breaches when a user first creates their password.
	CheckBreachOnCreation bool `json:"check_breach_on_creation,omitempty"`
	// CheckBreachOnAuthentication denotes whether to use the HaveIBeenPwned database to detect password
	// breaches when a user authenticates.
	CheckBreachOnAuthentication bool `json:"check_breach_on_authentication,omitempty"`
	// ValidateOnAuthentication notes whether to require a password reset on authentication if a user's current
	// password no longer meets the project's current policy requirements.
	ValidateOnAuthentication bool `json:"validate_on_authentication,omitempty"`
	// ValidationPolicy is the policy to use for password validation.
	ValidationPolicy ValidationPolicy `json:"validation_policy,omitempty"`
	// LudsMinPasswordLength is the minimum number of characters in a password if using a LUDS
	// validation_policy. This field is nil when using the ZXCVBN validation_policy.
	LudsMinPasswordLength *int32 `json:"luds_min_password_length,omitempty"`
	// LudsMinPasswordComplexity is the minimum number of "character types" in a password (Lowercase,
	// Uppercase, Digits, Symbols) when using a LUDS validation_policy. This field is nil when using the ZXCVBN
	// validation_policy.
	LudsMinPasswordComplexity *int32 `json:"luds_min_password_complexity,omitempty"`
}

// SetResponse: Response type for `PasswordStrengthConfig.Set`.
type SetResponse struct {
	// RequestID is a unique identifier to help with debugging the request.
	RequestID string `json:"request_id,omitempty"`
	// PasswordStrengthConfig is the password strength configuration for the environment.
	PasswordStrengthConfig PasswordStrengthConfig `json:"password_strength_config,omitempty"`
	// StatusCode is the HTTP status code for the response.
	StatusCode int `json:"status_code,omitempty"`
}

type ValidationPolicy string

const (
	ValidationPolicyUnknown ValidationPolicy = "UNKNOWN_VALIDATION_POLICY"
	ValidationPolicyZxcvbn  ValidationPolicy = "ZXCVBN"
	ValidationPolicyLuds    ValidationPolicy = "LUDS"
)

func ValidationPolicys() []ValidationPolicy {
	return []ValidationPolicy{
		ValidationPolicyZxcvbn,
		ValidationPolicyLuds,
	}
}
